/-
  CentralBimoduleKernel: the centre is where the commutative obstruction survives, and it
  settles the non-commutative real case

  SPINE LINK L6 — WALL W9, RUNG 2, closing `UNLOCK_WATCHLIST` 263. The previous unit proved
  that a COMMUTATIVE algebra of degree ≥ 2 never has a faithful regular bimodule over its own
  base field, and had to leave `M₂(ℂ)` over `ℝ` alone because `M₂(ℂ)` is not commutative. That
  entry named the route: **the central elements are where the commutative argument survives
  into the non-commutative case.** It does, and this is it.

  THE OBSERVATION, which is one line of algebra. If `c` commutes with everything in `A`, then
  left multiplication by `c` and right multiplication by `c` are the SAME operator, so
  `c ⊗ 1 - 1 ⊗ c` acts as zero. That is the whole of it, and it needs no commutativity of `A`
  — only of `c`.

  WHY THAT SETTLES THE CASE, AND WHY A COUNT COULD NOT. `UNLOCK_WATCHLIST` 262 asserted that
  the real regular bimodule of `M₂(ℂ)` is unfaithful and never proved it. **The dimension
  count that settles the commutative case is silent here**: over `ℝ`,
  `dim (A ⊗[ℝ] A) = 8 · 8 = 64` and `dim (End_ℝ A) = 8² = 64` — equal, so no
  injective-map-needs-room argument can decide it. What decides it is an explicit kernel
  element, and `i · 1` supplies one because it is central in `M₂(ℂ)` while lying outside
  `ℝ · 1`.

  AND THE PREVIOUS UNIT'S ABANDONED SECTION COULD HAVE BEEN WRITTEN, which is worth saying
  because the reason it was abandoned was wrong in an instructive way.
  `CommutativeBimoduleObstruction`'s header records that `Semiring (ℂ ⊗[ℝ] ℂ)`,
  `Algebra ℝ (ℂ ⊗[ℝ] ℂ)` and `IsScalarTower ℝ ℝ ℂ` are not found by `inferInstance`, and
  that a concrete section was therefore dropped. Probing again for `M₂(ℂ) ⊗[ℝ] M₂(ℂ)` shows
  the **same** failure, so it is at least not specific to `ℂ ⊗ ℂ` — two data points, and the
  scope beyond them is **not** claimed. **But `Module.Finite ℝ (M₂(ℂ) ⊗[ℝ] M₂(ℂ))` resolves
  immediately: only the RING structure fails, and faithfulness of a module is a LINEAR
  condition.** This file
  therefore uses `TensorProduct.lift` on a bilinear map and never asks for a ring structure on
  the tensor product at all. The previous unit's general theorem is still the stronger
  statement and nothing there is withdrawn; what was wrong was the inference that the concrete
  case was out of reach.

  WHAT IS PROVED.
  * **`regAction`** — the regular bimodule as an `ℝ`-LINEAR map `A ⊗[K] A →ₗ[K] Module.End K A`,
    `a ⊗ b ↦ (x ↦ a * x * b)`, built with `TensorProduct.lift` from `LinearMap.mk₂`. No ring
    structure on the tensor product is used or needed.
  * **`central_tmul_mem_ker`** — for any `K`-algebra `A` and any `c` commuting with everything,
    `c ⊗ 1 - 1 ⊗ c` is in the kernel. Fully general, and the one-line observation above.
  * **`sepForm`** — the separating functional `a ⊗ b ↦ (Tr a).im · (Tr b).re`. Needed because
    a count bounds a kernel without separating any element of it from `0`; this is the same
    role `mulTwistHom` played in the previous unit. **Assembled from `ℝ`-linear pieces rather
    than proved bilinear by hand**: `Complex.imLm` and `Complex.reLm` are already `ℝ`-linear,
    `Matrix.traceLinearMap (Fin 2) ℝ ℂ` is the trace over `ℝ`, and `LinearMap.compl₁₂` plugs
    both into multiplication — **zero bilinearity obligations**, where a first draft used
    `LinearMap.mk₂`, owed four, and had two of them fail because `Matrix.trace_smul` leaves an
    `ℝ • ℂ` that neither `Complex.smul_im` nor `exact?` will reduce.
  * **`iOne_central`**, **`iOne_tmul_ne_zero`** — `i · 1` is central in `M₂(ℂ)`, and
    `(i·1) ⊗ 1 - 1 ⊗ (i·1)` is non-zero, because `sepForm` sends it to `4`.
  * **`regAction_not_injective_M2C_over_R`** — **the theorem entry 262 asserted and did not
    prove**: the regular bimodule of `M₂(ℂ)` over `ℝ` is NOT faithful.

  WHAT IS **NOT** CLAIMED.
  * **Rung 2 is not climbed.** Like the previous unit this closes a route rather than opening
    one: together they say the doubled-module argument may not be run through a regular
    bimodule whenever the algebra has a centre bigger than the base field — which `ℂ ⊕ ℍ ⊕
    M₃(ℂ)` over `ℝ` certainly does.
  * **The Azumaya criterion is still cited and not proved.** That the regular bimodule is
    bijective *exactly* when `A` is central simple is Mathlib's `IsAzumaya`; this file proves
    only the easy direction's contrapositive at one algebra, by exhibiting a witness. The
    converse is not touched, and `¬ IsAzumaya ℝ (M₂(ℂ))` is not stated.
  * **No claim that the centre is the WHOLE kernel.** `central_tmul_mem_ker` produces kernel
    elements from central ones; whether the kernel is generated by them is the Azumaya
    statement again and is not proved here.
  * **Nothing about `J`, the grading, or any spectral-triple axiom.** This is a statement about
    one linear map.

  0 sorry. 0 new axioms. `#print axioms` on every declaration below:
  [propext, Classical.choice, Quot.sound].
-/

import CommutativeBimoduleObstruction

namespace CentralBimoduleKernel

open scoped TensorProduct

noncomputable section

/-! ## 1. The regular bimodule as a linear map -/

variable (K A : Type*) [Field K] [Ring A] [Algebra K A]

/-- `a ⊗ b ↦ (x ↦ a * x * b)`, bilinear. -/
def regBilin : A →ₗ[K] A →ₗ[K] Module.End K A :=
  LinearMap.mk₂ K (fun a b => (LinearMap.mulLeft K a).comp (LinearMap.mulRight K b))
    (fun a₁ a₂ b => by ext x; simp [add_mul])
    (fun r a b => by ext x; simp)
    (fun a b₁ b₂ => by ext x; simp [mul_add])
    (fun r a b => by ext x; simp)

/-- **The regular bimodule, linearly.** No ring structure on the tensor product is used —
faithfulness of a module is a linear condition, and the ring instance for a concrete
`ℂ`-algebra tensored over `ℝ` is the one `inferInstance` cannot find. -/
def regAction : A ⊗[K] A →ₗ[K] Module.End K A := TensorProduct.lift (regBilin K A)

@[simp]
theorem regAction_tmul (a b x : A) : regAction K A (a ⊗ₜ[K] b) x = a * x * b := by
  simp [regAction, regBilin, mul_assoc]

/-- **The observation, and it is one line of algebra.** If `c` commutes with everything then
left and right multiplication by `c` are the same operator, so `c ⊗ 1 - 1 ⊗ c` acts as zero.
No commutativity of `A` is used — only of `c`. -/
theorem central_tmul_mem_ker (c : A) (hc : ∀ x : A, c * x = x * c) :
    regAction K A (c ⊗ₜ[K] 1 - 1 ⊗ₜ[K] c) = 0 := by
  ext x
  simp only [map_sub, LinearMap.sub_apply, regAction_tmul, mul_one, one_mul,
    LinearMap.zero_apply]
  rw [hc x, sub_self]

end

/-! ## 2. `M₂(ℂ)` over `ℝ`: the case the count cannot decide -/

noncomputable section MatrixCase

/-- The trace as an `ℝ`-linear map into `ℂ`. -/
def trR : Matrix (Fin 2) (Fin 2) ℂ →ₗ[ℝ] ℂ := Matrix.traceLinearMap (Fin 2) ℝ ℂ

/-- The separating form `a ⊗ b ↦ (Tr a).im · (Tr b).re`, assembled from `ℝ`-linear pieces
rather than proved bilinear by hand: `Complex.imLm` and `Complex.reLm` are already `ℝ`-linear,
`trR` is the trace over `ℝ`, and `LinearMap.compl₁₂` plugs both into multiplication. **Zero
bilinearity obligations**, where a `LinearMap.mk₂` needed four and two of them fought back. -/
def sepBilin : Matrix (Fin 2) (Fin 2) ℂ →ₗ[ℝ] Matrix (Fin 2) (Fin 2) ℂ →ₗ[ℝ] ℝ :=
  (LinearMap.mul ℝ ℝ).compl₁₂ (Complex.imLm ∘ₗ trR) (Complex.reLm ∘ₗ trR)

def sepForm : Matrix (Fin 2) (Fin 2) ℂ ⊗[ℝ] Matrix (Fin 2) (Fin 2) ℂ →ₗ[ℝ] ℝ :=
  TensorProduct.lift sepBilin

@[simp]
theorem sepForm_tmul (a b : Matrix (Fin 2) (Fin 2) ℂ) :
    sepForm (a ⊗ₜ[ℝ] b) = (Matrix.trace a).im * (Matrix.trace b).re := by
  simp [sepForm, sepBilin, trR, Matrix.traceLinearMap]

/-- `i · 1` — central in `M₂(ℂ)` and outside `ℝ · 1`, which is exactly what the argument needs
and exactly what a commutative algebra of degree one would not have. -/
def iOne : Matrix (Fin 2) (Fin 2) ℂ := Complex.I • (1 : Matrix (Fin 2) (Fin 2) ℂ)

theorem iOne_central (x : Matrix (Fin 2) (Fin 2) ℂ) : iOne * x = x * iOne := by
  rw [iOne, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul, Matrix.mul_one]

theorem trace_iOne : Matrix.trace iOne = 2 * Complex.I := by
  simp [iOne, Matrix.trace_smul, smul_eq_mul]
  ring

/-- The kernel element is **non-zero**, because `sepForm` sends it to `4`. -/
theorem iOne_tmul_ne_zero :
    (iOne ⊗ₜ[ℝ] (1 : Matrix (Fin 2) (Fin 2) ℂ)
      - (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₜ[ℝ] iOne) ≠ 0 := by
  intro h
  have h4 : sepForm (iOne ⊗ₜ[ℝ] (1 : Matrix (Fin 2) (Fin 2) ℂ)
      - (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₜ[ℝ] iOne) = 0 := by rw [h, map_zero]
  rw [map_sub, sepForm_tmul, sepForm_tmul, trace_iOne, Matrix.trace_one] at h4
  norm_num at h4

/-- **THE THEOREM `UNLOCK_WATCHLIST` 262 ASSERTED AND DID NOT PROVE.** The regular bimodule of
`M₂(ℂ)` over `ℝ` is not faithful — and note that the dimension count which settles the
commutative case is SILENT here, both sides being 64-dimensional over `ℝ`. What decides it is
this witness. -/
theorem regAction_not_injective_M2C_over_R :
    ¬ Function.Injective (regAction ℝ (Matrix (Fin 2) (Fin 2) ℂ)) := by
  intro hinj
  exact iOne_tmul_ne_zero
    (hinj ((central_tmul_mem_ker ℝ _ iOne iOne_central).trans (map_zero _).symm))

end MatrixCase

end CentralBimoduleKernel
