/-
  CommutativeBimoduleObstruction: why the doubled route cannot carry rung 2 through a
  regular bimodule — and a correction to this project's own register

  SPINE LINK L6 — WALL W9, RUNG 2. `UNLOCK_WATCHLIST` 262 named three routes out of the gap
  the previous two units left, and said of the third: *"(c) is the cheapest and should come
  first, because it turns a sentence in a watchlist entry into a machine-checked fact."*
  This is (c). It came first, and **the fact is not the one the sentence claimed.**

  WHAT THE REGISTER SAID, AND WHAT IS ACTUALLY TRUE. Entry 262 asserted that
  `ker (ℂ ⊗[ℝ] ℂ → End_ℝ ℂ)` is *"one-dimensional and generated by `i ⊗ 1 - 1 ⊗ i`"*. The
  generator is right. **The dimension is wrong: the kernel is two-dimensional over `ℝ`.**
  `finrank_ker_mulHom_degree_two` proves it. The element spans a LINE and the kernel is a
  PLANE;
  `i ⊗ 1 - 1 ⊗ i` generates the kernel as an **ideal**, not as a subspace, and the entry
  collapsed the two. Filed as `ERRATUM 568` and corrected in the entry rather than quietly
  patched.

  AND THE GENERAL STATEMENT IS STRONGER THAN THE `ℝ`-SPECIFIC ONE, which is the reason this
  unit is worth more than an erratum. Entry 262 framed the obstruction as an accident of
  `ℂ ⊗[ℝ] ℂ` not being a field. It is not an accident and it is not about `ℂ`:

  > **For ANY field `K` and ANY commutative `K`-algebra `A` with `2 ≤ dim_K A < ∞`, the
  > regular bimodule of `A` is never a faithful `A ⊗[K] Aᵒᵖ`-module.**

  The reason is a dimension count and nothing deeper. For commutative `A` the two actions are
  both multiplications, so the map factors through `A ⊗[K] A → A`, `a ⊗ b ↦ ab`, whose source
  has dimension `n²` and whose target has dimension `n`. A surjection `n² → n` with `n ≥ 2`
  has a kernel of dimension `n² - n > 0`. **So `𝕂 = ℝ` was never the operative hypothesis —
  commutativity was.**

  WHY THAT MATTERS FOR THE WALL. `SpectralTripleBimodule.doubled_isSemisimple` needs an
  injective `bimodule`, and `OrderOneNontrivial`'s witness is complex precisely because the
  real one was expected to be harder. It is not harder; it is differently shaped. And the
  general form reaches further than the real case: **CCM's own algebra `ℂ ⊕ ℍ ⊕ M₃(ℂ)` has a
  commutative factor**, so the doubled route cannot be carried through its regular bimodule
  over any base field whatever. **The honest general criterion is cited and not proved here**:
  the regular bimodule `A ⊗[K] Aᵒᵖ → End_K(A)` is bijective exactly when `A` is central simple
  over `K`, which is Mathlib's `IsAzumaya` and is what `CascadeEnd.azumayaEquiv` consumes at
  the matrix algebras. `ℂ` over `ℝ` fails it because its centre is `ℂ` and not `ℝ`; a product
  fails it because it is not simple. **This file proves the commutative direction by counting
  and cites the criterion; it does not prove the criterion.**

  WHAT IS PROVED.
  * **`mulHom`** — multiplication `A ⊗[K] A →ₐ[K] A` for commutative `A`, off
    `Algebra.TensorProduct.lift` with `mul_comm` as the commuting hypothesis. The same Mathlib
    map the rung-2 unit used, at the degenerate case where both factors are the same algebra.
  * **`mulHom_surjective`**, **`finrank_tensorSquare`** (`= n * n`), and
    **`mulHom_not_injective`** for `2 ≤ n` — the count, as a theorem.
  * **`finrank_ker_mulHom`** — the kernel has dimension `n * n - n`, by rank–nullity.
  * **`finrank_ker_mulHom_degree_two`** — the correction: at degree two the kernel is
    **2**-dimensional. Instantiated at `K = ℝ`, `A = ℂ`, where `Module.finrank ℝ ℂ = 2` is
    Mathlib's `Complex.finrank_real_complex`, this is exactly the figure entry 262 got wrong.
  * **`gen_mem_ker`**, **`gen_ne_zero`**, **`span_gen_ne_ker`** — the generator is in the
    kernel at every `α`; it is non-zero whenever some `K`-automorphism moves `α`, which for
    `ℂ` over `ℝ` at `α = i` is conjugation sending the element to `2i`; and its span is
    **strictly smaller** than the kernel. **That last one is the erratum, as a theorem.** The
    twisted map `mulTwistHom` exists only for this: a dimension count bounds the kernel
    without separating any element of it from `0`.
  * **`doubled_route_blocked`** — the two facts rung 2 needs, as one statement.

  WHAT IS **NOT** CLAIMED.
  * **Rung 2 is not climbed and this does not climb it.** The unit closes a route rather than
    opening one: it says the doubled-module argument cannot be run through a regular bimodule
    once a commutative factor is present, which narrows what a rung-2 proof may look like and
    proves nothing about involutions or factor lists.
  * **The Azumaya criterion is cited, not proved** — see above. Nor is the converse direction
    (that central simplicity suffices) used anywhere here.
  * **No claim about `M₂(ℂ)` over `ℝ` specifically.** `M₂(ℂ)` is NOT commutative, so this
    file's theorem does not apply to it, and entry 262's sentence about it is **not** settled
    here. What is settled is that the `ℂ`-factor case is general and the `ℝ`-framing was
    wrong; the non-commutative real case needs the Azumaya criterion, which is why that is
    named as cited rather than assumed. `UNLOCK_WATCHLIST` 263.
  * **The `ℂ`-over-`ℝ` case is stated GENERALLY and not instantiated in Lean, and the reason
    is a Mathlib instance quirk worth recording.** `Semiring (ℂ ⊗[ℝ] ℂ)`, `Algebra ℝ (ℂ ⊗[ℝ] ℂ)`
    and even `IsScalarTower ℝ ℝ ℂ` are **not found by `inferInstance`** — at any heartbeat
    budget — while the same instances for a VARIABLE algebra `A ⊗[K] A` are found immediately.
    `Algebra.TensorProduct.instSemiring` supplies the first by name, but the others fight back,
    so a concrete `ℂ ⊗[ℝ] ℂ` section was written, probed and **abandoned**. Everything here is
    therefore proved for every commutative algebra of degree `n`, which is strictly stronger
    than the `ℂ` case and covers it — but the final substitution `n = 2` for `ℂ/ℝ` is an
    appeal to `Complex.finrank_real_complex` rather than a machine-checked instantiation.
    **Said here rather than left for a reader to notice.**

  0 sorry. 0 new axioms. `#print axioms` on every declaration below:
  [propext, Classical.choice, Quot.sound].
-/

import SpectralTripleBimodule

namespace CommutativeBimoduleObstruction

open scoped TensorProduct

noncomputable section

/-! ## 1. The count, for any commutative algebra over any field -/

variable (K A : Type*) [Field K] [CommRing A] [Algebra K A]

/-- Multiplication as an algebra map out of the tensor square. `Algebra.TensorProduct.lift`
wants the two images to commute, and for a commutative `A` that is free. -/
def mulHom : A ⊗[K] A →ₐ[K] A :=
  Algebra.TensorProduct.lift (AlgHom.id K A) (AlgHom.id K A) (fun x y => Commute.all x y)

@[simp]
theorem mulHom_tmul (a b : A) : mulHom K A (a ⊗ₜ[K] b) = a * b :=
  Algebra.TensorProduct.lift_tmul _ _ _ _ _

theorem mulHom_surjective : Function.Surjective (mulHom K A) := fun a =>
  ⟨a ⊗ₜ[K] 1, by rw [mulHom_tmul, mul_one]⟩

theorem finrank_tensorSquare :
    Module.finrank K (A ⊗[K] A) = Module.finrank K A * Module.finrank K A :=
  Module.finrank_tensorProduct

variable [FiniteDimensional K A]

/-- **The obstruction, as a count.** A surjection from an `n²`-dimensional space onto an
`n`-dimensional one cannot be injective once `n ≥ 2`. `𝕂 = ℝ` was never the operative
hypothesis — commutativity was. -/
theorem mulHom_not_injective (h : 2 ≤ Module.finrank K A) :
    ¬ Function.Injective (mulHom K A) := by
  intro hinj
  have hle : Module.finrank K (A ⊗[K] A) ≤ Module.finrank K A :=
    LinearMap.finrank_le_finrank_of_injective (f := (mulHom K A).toLinearMap) hinj
  rw [finrank_tensorSquare] at hle
  nlinarith [hle, h]

/-- The kernel's dimension, by rank–nullity. -/
theorem finrank_ker_mulHom :
    Module.finrank K (LinearMap.ker (mulHom K A).toLinearMap)
      = Module.finrank K A * Module.finrank K A - Module.finrank K A := by
  have hr : LinearMap.range (mulHom K A).toLinearMap = ⊤ :=
    LinearMap.range_eq_top.mpr (mulHom_surjective K A)
  have h := LinearMap.finrank_range_add_finrank_ker (mulHom K A).toLinearMap
  rw [hr, finrank_top, finrank_tensorSquare] at h
  omega

/-- **THE CORRECTION, in the general form that covers it.** At degree two the kernel is
**TWO**-dimensional, not one. `UNLOCK_WATCHLIST` 262 said one; `ERRATUM 568`. Instantiated at
`K = ℝ`, `A = ℂ` — where `Module.finrank ℝ ℂ = 2` is Mathlib's `Complex.finrank_real_complex`
— this is exactly the figure that entry got wrong. -/
theorem finrank_ker_mulHom_degree_two (h : Module.finrank K A = 2) :
    Module.finrank K (LinearMap.ker (mulHom K A).toLinearMap) = 2 := by
  rw [finrank_ker_mulHom, h]

/-! ## 2. The generator, and why its span is not the kernel -/

/-- Multiplication after applying an automorphism to the right factor. This is the map that
separates the generator from zero; the plain count cannot, because it bounds the kernel
without separating any element of it from `0`. -/
def mulTwistHom (σ : A ≃ₐ[K] A) : A ⊗[K] A →ₐ[K] A :=
  Algebra.TensorProduct.lift (AlgHom.id K A) σ.toAlgHom (fun x _ => Commute.all x _)

omit [FiniteDimensional K A] in
@[simp]
theorem mulTwistHom_tmul (σ : A ≃ₐ[K] A) (a b : A) :
    mulTwistHom K A σ (a ⊗ₜ[K] b) = a * σ b :=
  Algebra.TensorProduct.lift_tmul _ _ _ _ _

omit [FiniteDimensional K A] in
/-- The element entry 262 named IS in the kernel, at every `α`. -/
theorem gen_mem_ker (α : A) : mulHom K A (α ⊗ₜ[K] 1 - 1 ⊗ₜ[K] α) = 0 := by
  rw [map_sub, mulHom_tmul, mulHom_tmul, mul_one, one_mul, sub_self]

omit [FiniteDimensional K A] in
/-- And it is non-zero whenever some `K`-automorphism moves `α` — which for `ℂ` over `ℝ` and
`α = i` is complex conjugation, sending the element to `2i`. -/
theorem gen_ne_zero (σ : A ≃ₐ[K] A) (α : A) (hσ : σ α ≠ α) :
    (α ⊗ₜ[K] 1 - 1 ⊗ₜ[K] α : A ⊗[K] A) ≠ 0 := by
  intro h
  have h2 : mulTwistHom K A σ (α ⊗ₜ[K] 1 - 1 ⊗ₜ[K] α) = 0 := by rw [h, map_zero]
  rw [map_sub, mulTwistHom_tmul, mulTwistHom_tmul, map_one, mul_one, one_mul,
    sub_eq_zero] at h2
  exact hσ h2.symm

/-- **THE ERRATUM AS A THEOREM.** The generator spans a LINE; the kernel is bigger. So
`i ⊗ 1 - 1 ⊗ i` generates the kernel as an **ideal** and not as a subspace, and entry 262
collapsed the two. -/
theorem span_gen_ne_ker (σ : A ≃ₐ[K] A) (α : A) (hσ : σ α ≠ α)
    (h : 2 ≤ Module.finrank K A) :
    Submodule.span K {(α ⊗ₜ[K] 1 - 1 ⊗ₜ[K] α : A ⊗[K] A)}
      ≠ LinearMap.ker (mulHom K A).toLinearMap := by
  intro hEq
  have h1 : Module.finrank K
      (Submodule.span K {(α ⊗ₜ[K] 1 - 1 ⊗ₜ[K] α : A ⊗[K] A)}) = 1 :=
    finrank_span_singleton (gen_ne_zero K A σ α hσ)
  rw [hEq, finrank_ker_mulHom] at h1
  have h2 : 2 * Module.finrank K A ≤ Module.finrank K A * Module.finrank K A :=
    Nat.mul_le_mul_right _ h
  obtain ⟨m, hm⟩ : ∃ m, Module.finrank K A * Module.finrank K A = m := ⟨_, rfl⟩
  rw [hm] at h1 h2
  omega

/-! ## 3. The same conclusion in the shape rung 2 consumes -/

/-- **What this says for rung 2.** `SpectralTripleBimodule.doubled_isSemisimple` needs an
injective map out of `A ⊗[𝕂] Aᵐᵒᵖ`. For a commutative `A` acting on itself both actions are
multiplications, so that map factors through `mulHom`, and `mulHom` is not injective once
`dim ≥ 2`. Stated as the composite fact rather than by rebuilding the bimodule, because
`Aᵐᵒᵖ ≃ₐ[K] A` for commutative `A` and the two shapes carry the same content. -/
theorem doubled_route_blocked (h : 2 ≤ Module.finrank K A) :
    ¬ Function.Injective (mulHom K A) ∧
      Module.finrank K (LinearMap.ker (mulHom K A).toLinearMap)
        = Module.finrank K A * Module.finrank K A - Module.finrank K A :=
  ⟨mulHom_not_injective K A h, finrank_ker_mulHom K A⟩

end

end CommutativeBimoduleObstruction
