import FieldAutOrder
import GraphAutDegree

/-!
# The connected case, settled: a tree, all of whose symmetries are involutions, with a repeated
Laplacian eigenvalue

`FieldInvolutionConverse` showed that *every automorphism is an involution* does **not** imply a
simple spectrum, and said plainly that its witness — two vertices with no edge — was disconnected,
so it failed for a reason recorded an hour earlier. It filed the repair as the question worth
settling: **connected, and every automorphism an involution — does that force a simple spectrum?**
It named `AsymmetricGraph.asymGraph` as the natural candidate and recorded that nothing in this
estate computes its spectrum.

**No spectrum needs computing.** A graph with two disjoint pairs of twins of the same degree has a
repeated eigenvalue for a reason one can see: the difference of each twin pair is an eigenvector,
and the two differences are independent. Arrange the rest of the graph so that no automorphism
exchanges the pairs, and every automorphism is an involution.

## What is proved

**`twinGraph`** — a **tree** on eight vertices: pendants `0, 1` on `2`, pendants `3, 4` on `5`, the
edge `2–5`, and a tail `5–6–7`. **`twinGraph_connected`** — it is connected, by explicit
reachability from `2`.

**`twinGraph_aut_involutive`** — **every automorphism is an involution**, by degrees alone. The
degree sequence is `1, 1, 3, 1, 1, 4, 2, 1`, so `2`, `5` and `6` are each alone in their degree and
fixed (`GraphAutDegree.IsGraphAut.eq_of_degree_unique`); `7` is then the only degree-`1` vertex
adjacent to the fixed `6`, so it is fixed too; and the degree-`1` vertices adjacent to `2` are
exactly `{0, 1}` and those adjacent to `5` exactly `{3, 4}`, so each pair is preserved — and an
injection of a two-element set into itself is an involution. **No enumeration of the `40320`
permutations is done**, and the tail `5–6–7` is exactly what stops the two halves being exchanged.

**`lap_v01`, `lap_v34`, `two_le_finrank_eigenspace`** — `e₀ − e₁` and `e₃ − e₄` are both
eigenvectors at eigenvalue `1`, and they are independent, so that eigenspace has dimension at least
two.

**`not_finrank_lapMatrix_le_one`, `not_injective_lapMatrix_eigenvalues`,
`not_eigenvalues_injective_green`** — **so the chain's hypothesis fails on a connected graph all of
whose automorphisms are involutions.** The answer to the question `FieldInvolutionConverse` left is
**no**: connectivity does not repair the converse.

## What is NOT here

**THE SPECTRUM IS NOT COMPUTED, AND THE MULTIPLICITY IS A LOWER BOUND.** Two independent
eigenvectors at `1` are exhibited; **nothing here says the multiplicity is exactly two**, and no
other eigenvalue of `twinGraph` is named. The eight-vertex characteristic polynomial is not touched.

**`AsymmetricGraph.asymGraph` IS STILL UNTOUCHED.** The candidate the previous unit named is not
used and **its spectrum is still computed nowhere in this estate** — counted, not assumed
(`ERRATUM 450`): `AsymmetricGraph.lean` contains the word *eigenvalue* zero times. The question it
was named for is answered by a different graph, so the candidate is now **unneeded** rather than
**pending**, which is a change of status and not a closure of that computation.

**THE AUTOMORPHISM GROUP IS NOT IDENTIFIED.** It is `(ℤ/2)²` — generated by the two transpositions
— and **this file proves only that every element squares to the identity**, which is all the chain's
involution theorem talks about. **No group is constructed and no order is computed.**

**NO CHARACTERISATION, AND THE SCOREBOARD BARELY MOVES.** This adds one graph to the failing side.
It does not say which graphs satisfy the hypothesis, and the standing `UNLOCK_WATCHLIST` question is
untouched. What it does is **close one candidate repair**: adding connectivity to *every
automorphism is an involution* does not make it a characterisation. **No other strengthening is
tested here**, and naming this one as the obvious repair is `FieldInvolutionConverse`'s judgement,
not a claim that it was the only one.

**THE TWIN ARGUMENT IS NOT STATED IN GENERAL.** *Two disjoint pairs of non-adjacent twins of equal
degree give a repeated Laplacian eigenvalue* is a general theorem, and **this file proves it for one
graph by direct computation instead**. Not attempted, no cost claimed (`ERRATUM 246`).

⚠ **IT IS STATED IN GENERAL ONE UNIT LATER, AND THE PARAGRAPH ABOVE IS KEPT AS WRITTEN**
(`ERRATUM 94`). `LaplacianTwins.two_le_finrank_of_twin_pairs`, and it is **cleaner than the sentence
above in two ways**: *non-adjacent* is not a hypothesis but a consequence
(`LaplacianTwins.not_adj_of_neighborFinset_eq` — twins with the same neighbours would each be their
own neighbour), and *disjoint* is too strong, since the pairs may share a vertex.
`LaplacianTwins.twinGraph_not_injective` re-derives this file's conclusion for **this** graph in one
line. §4's eigenvector computation is kept and not deleted.

**No wall moves.** `W1`'s open part is `OS0` and `OS4`, and `OS1` in its continuum sense.

**THE HYPOTHESES, READ OFF THE BINDERS** (`ERRATUM 455`): **one of the twenty-six declarations takes
a mass**, `not_eigenvalues_injective_green`, and only because `green` is defined as an inverse.
Everything else is about a graph and its Laplacian, and `twinGraph_aut_involutive` takes only the
automorphism hypothesis.

Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.

-/

namespace FieldTwinSpectrum

open SimpleGraph FieldAutInvariance GraphAutDegree Matrix GraphLaplacian

/-! ## 1. The graph -/

/-- Adjacency of `twinGraph`: two pendants `0, 1` on `2`; two pendants `3, 4` on `5`; the edge
`2–5`; and a tail `5–6–7`. -/
def twinAdj : Fin 8 → Fin 8 → Bool
  | 0, 2 | 2, 0 => true
  | 1, 2 | 2, 1 => true
  | 2, 5 | 5, 2 => true
  | 3, 5 | 5, 3 => true
  | 4, 5 | 5, 4 => true
  | 5, 6 | 6, 5 => true
  | 6, 7 | 7, 6 => true
  | _, _ => false

/-- **A tree with two twin pairs and no automorphism of order more than two.** -/
def twinGraph : SimpleGraph (Fin 8) where
  Adj u v := twinAdj u v = true
  symm := by intro u v h; revert u v; decide
  loopless := ⟨by intro u h; revert u; decide⟩

instance : DecidableRel twinGraph.Adj := fun u v =>
  inferInstanceAs (Decidable (twinAdj u v = true))

theorem twinGraph_degrees :
    ∀ v : Fin 8, twinGraph.degree v = ![1, 1, 3, 1, 1, 4, 2, 1] v := by decide

theorem nbr_eq : ∀ p : Fin 8, twinGraph.neighborFinset p =
    ![{2}, {2}, {0, 1, 5}, {5}, {5}, {2, 3, 4, 6}, {5, 7}, {6}] p := by decide

/-! ## 2. It is connected -/

theorem reach_two : ∀ v : Fin 8, twinGraph.Reachable 2 v := by
  intro v
  fin_cases v
  · exact (SimpleGraph.Adj.reachable (by decide : twinGraph.Adj 2 0))
  · exact (SimpleGraph.Adj.reachable (by decide : twinGraph.Adj 2 1))
  · exact SimpleGraph.Reachable.refl 2
  · exact ((by decide : twinGraph.Adj 2 5).reachable).trans
      ((by decide : twinGraph.Adj 5 3).reachable)
  · exact ((by decide : twinGraph.Adj 2 5).reachable).trans
      ((by decide : twinGraph.Adj 5 4).reachable)
  · exact (by decide : twinGraph.Adj 2 5).reachable
  · exact ((by decide : twinGraph.Adj 2 5).reachable).trans
      ((by decide : twinGraph.Adj 5 6).reachable)
  · exact (((by decide : twinGraph.Adj 2 5).reachable).trans
      ((by decide : twinGraph.Adj 5 6).reachable)).trans
      ((by decide : twinGraph.Adj 6 7).reachable)

theorem twinGraph_connected : twinGraph.Connected :=
  SimpleGraph.Connected.mk fun u v => ((reach_two u).symm).trans (reach_two v)

/-! ## 3. Every automorphism is an involution -/

theorem fix_two {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 2 = 2 :=
  GraphAutDegree.IsGraphAut.eq_of_degree_unique h (by decide)

theorem fix_five {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 5 = 5 :=
  GraphAutDegree.IsGraphAut.eq_of_degree_unique h (by decide)

theorem fix_six {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 6 = 6 :=
  GraphAutDegree.IsGraphAut.eq_of_degree_unique h (by decide)

theorem fix_seven {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 7 = 7 := by
  have hd : twinGraph.degree (θ 7) = 1 := by
    rw [GraphAutDegree.IsGraphAut.degree h]; decide
  have ha : twinGraph.Adj (θ 7) 6 := by
    have h1 := (h 7 6).mpr (by decide)
    rwa [fix_six h] at h1
  revert hd ha
  generalize θ 7 = x
  revert x
  decide

theorem map_zero_mem {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 0 = 0 ∨ θ 0 = 1 := by
  have hd : twinGraph.degree (θ 0) = 1 := by
    rw [GraphAutDegree.IsGraphAut.degree h]; decide
  have ha : twinGraph.Adj (θ 0) 2 := by
    have h1 := (h 0 2).mpr (by decide)
    rwa [fix_two h] at h1
  revert hd ha
  generalize θ 0 = x
  revert x
  decide

theorem map_one_mem {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 1 = 0 ∨ θ 1 = 1 := by
  have hd : twinGraph.degree (θ 1) = 1 := by
    rw [GraphAutDegree.IsGraphAut.degree h]; decide
  have ha : twinGraph.Adj (θ 1) 2 := by
    have h1 := (h 1 2).mpr (by decide)
    rwa [fix_two h] at h1
  revert hd ha
  generalize θ 1 = x
  revert x
  decide

theorem map_three_mem {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 3 = 3 ∨ θ 3 = 4 := by
  have hd : twinGraph.degree (θ 3) = 1 := by
    rw [GraphAutDegree.IsGraphAut.degree h]; decide
  have ha : twinGraph.Adj (θ 3) 5 := by
    have h1 := (h 3 5).mpr (by decide)
    rwa [fix_five h] at h1
  revert hd ha
  generalize θ 3 = x
  revert x
  decide

theorem map_four_mem {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) : θ 4 = 3 ∨ θ 4 = 4 := by
  have hd : twinGraph.degree (θ 4) = 1 := by
    rw [GraphAutDegree.IsGraphAut.degree h]; decide
  have ha : twinGraph.Adj (θ 4) 5 := by
    have h1 := (h 4 5).mpr (by decide)
    rwa [fix_five h] at h1
  revert hd ha
  generalize θ 4 = x
  revert x
  decide

/-- **EVERY AUTOMORPHISM OF `twinGraph` IS AN INVOLUTION**, by degrees alone: `2`, `5`, `6` and `7`
are fixed, and the pairs `{0, 1}` and `{3, 4}` are each preserved, on which an injection is an
involution. **No enumeration of the `40320` permutations is done.** -/
theorem twinGraph_aut_involutive {θ : Fin 8 ≃ Fin 8} (h : IsGraphAut twinGraph θ) (p : Fin 8) :
    θ (θ p) = p := by
  have h0 : θ (θ 0) = 0 := by
    rcases map_zero_mem h with h0 | h0
    · rw [h0, h0]
    · rw [h0]
      rcases map_one_mem h with h1 | h1
      · exact h1
      · exact absurd (θ.injective (h0.trans h1.symm)) (by decide)
  have h1 : θ (θ 1) = 1 := by
    rcases map_one_mem h with h1 | h1
    · rw [h1]
      rcases map_zero_mem h with h0 | h0
      · exact absurd (θ.injective (h1.trans h0.symm)) (by decide)
      · exact h0
    · rw [h1, h1]
  have h3 : θ (θ 3) = 3 := by
    rcases map_three_mem h with h3 | h3
    · rw [h3, h3]
    · rw [h3]
      rcases map_four_mem h with h4 | h4
      · exact h4
      · exact absurd (θ.injective (h3.trans h4.symm)) (by decide)
  have h4 : θ (θ 4) = 4 := by
    rcases map_four_mem h with h4 | h4
    · rw [h4]
      rcases map_three_mem h with h3 | h3
      · exact absurd (θ.injective (h4.trans h3.symm)) (by decide)
      · exact h3
    · rw [h4, h4]
  have h2 : θ (θ 2) = 2 := by rw [fix_two h, fix_two h]
  have h5 : θ (θ 5) = 5 := by rw [fix_five h, fix_five h]
  have h6 : θ (θ 6) = 6 := by rw [fix_six h, fix_six h]
  have h7 : θ (θ 7) = 7 := by rw [fix_seven h, fix_seven h]
  fin_cases p <;> assumption

/-! ## 4. Two independent eigenvectors at the eigenvalue 1 -/

def v01 : Fin 8 → ℝ := fun i => (if i = 0 then 1 else 0) - (if i = 1 then 1 else 0)

def v34 : Fin 8 → ℝ := fun i => (if i = 3 then 1 else 0) - (if i = 4 then 1 else 0)

theorem lap_v01 : twinGraph.lapMatrix ℝ *ᵥ v01 = (1 : ℝ) • v01 := by
  funext p
  rw [SimpleGraph.lapMatrix_mulVec_apply, nbr_eq p, twinGraph_degrees p]
  fin_cases p <;> norm_num +decide [v01, Finset.sum_sub_distrib, Finset.sum_ite_eq']

theorem lap_v34 : twinGraph.lapMatrix ℝ *ᵥ v34 = (1 : ℝ) • v34 := by
  funext p
  rw [SimpleGraph.lapMatrix_mulVec_apply, nbr_eq p, twinGraph_degrees p]
  fin_cases p <;> norm_num +decide [v34, Finset.sum_sub_distrib, Finset.sum_ite_eq']

theorem mem_ker_v01 : v01 ∈ LinearMap.ker
    (Matrix.toLin' (twinGraph.lapMatrix ℝ) - (1 : ℝ) • LinearMap.id) :=
  (FieldCycleRotation.mem_eigenspace_iff_mulVec _ _ _).mpr lap_v01

theorem mem_ker_v34 : v34 ∈ LinearMap.ker
    (Matrix.toLin' (twinGraph.lapMatrix ℝ) - (1 : ℝ) • LinearMap.id) :=
  (FieldCycleRotation.mem_eigenspace_iff_mulVec _ _ _).mpr lap_v34

theorem linearIndependent_v : LinearIndependent ℝ ![v01, v34] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  constructor
  · have h0 := congrFun hst 0
    simpa [v01, v34] using h0
  · have h3 := congrFun hst 3
    simpa [v01, v34] using h3

theorem two_le_finrank_eigenspace :
    2 ≤ Module.finrank ℝ (LinearMap.ker
      (Matrix.toLin' (twinGraph.lapMatrix ℝ) - (1 : ℝ) • LinearMap.id)) := by
  have hsub : Submodule.span ℝ (Set.range ![v01, v34]) ≤ LinearMap.ker
      (Matrix.toLin' (twinGraph.lapMatrix ℝ) - (1 : ℝ) • LinearMap.id) := by
    rw [Submodule.span_le, Set.range_subset_iff]
    intro i
    fin_cases i
    · exact mem_ker_v01
    · exact mem_ker_v34
  have hcard : Module.finrank ℝ (Submodule.span ℝ (Set.range ![v01, v34])) = 2 := by
    rw [finrank_span_eq_card linearIndependent_v]
    simp
  rw [← hcard]
  exact Submodule.finrank_mono hsub

/-! ## 5. So the hypothesis fails, on a connected graph with only involutive automorphisms -/

theorem not_finrank_lapMatrix_le_one :
    ¬ (∀ ν : ℝ, Module.finrank ℝ (LinearMap.ker
        (Matrix.toLin' (twinGraph.lapMatrix ℝ) - ν • LinearMap.id)) ≤ 1) := by
  intro hdim
  have h1 := hdim 1
  have h2 := two_le_finrank_eigenspace
  omega

/-- **THE CONNECTED CASE IS SETTLED, AND IN THE SAME DIRECTION.** `twinGraph` is connected, every
one of its automorphisms is an involution, and its Laplacian spectrum is degenerate. -/
theorem not_injective_lapMatrix_eigenvalues :
    ¬ Function.Injective
      (FieldSimpleConverse.lapMatrix_isHermitian twinGraph).eigenvalues := fun hinj =>
  not_finrank_lapMatrix_le_one
    (FieldSimpleConverse.finrank_lapMatrix_le_one_iff_injective.mpr hinj)

theorem not_eigenvalues_injective_green {mass : ℝ} (hmass : mass ≠ 0)
    (hH : (green twinGraph mass).IsHermitian) : ¬ Function.Injective hH.eigenvalues :=
  fun hinj => not_finrank_lapMatrix_le_one
    (FieldSimpleConverse.finrank_lapMatrix_le_one_of_eigenvalues_injective hmass hH hinj)

end FieldTwinSpectrum
