import FieldAutInvariance
import LatticeOddVanishing

/-!
# One symmetry theorem for the field, of which the estate's two are instances

This estate has **two** field-level symmetry statements and its registers describe them as two
different kinds. `FieldAutInvariance.gaussianField_map_perm`: the Gaussian field is invariant under
every graph automorphism. `LatticeOddVanishing.gaussianField_map_neg`: it is invariant under
`ω ↦ −ω`, which — the `UNLOCK_WATCHLIST` OS block's words — *"is not induced by any permutation of
sites, so `green_congr` and `gaussianField_map_perm` say nothing about it"*.

**Both proofs are the same three moves**: `charFun_map_isometry`, the Gaussian's characteristic
function twice, and then a fact about the propagator's quadratic form. **Only the third move
differs**, and in each case it says the map preserves that form.

`PROOF_STRATEGY` §7 rule 3, and the hypothesis removed is *what kind of map it is*.

## What is proved

**`gaussianField_map_isometry`** — for **any** linear isometry `T` of `EuclideanSpace ℝ V` whose
inverse preserves the propagator's quadratic form, `(gaussianField G m).map T = gaussianField G m`.
No permutation, no sign, no graph automorphism: **preserving the covariance form is the whole
hypothesis**, and it is visibly the right one, because it is exactly what the characteristic
function sees.

**`gaussianField_map_perm'`** and **`gaussianField_map_neg'`** — the estate's two statements, each
in one line from the general one. Both originals **stay as written and are not edited**
(`ERRATUM 94`, `ERRATUM 337`); they keep their consumers, and these record that they are instances.

**`gaussianField_map_neg_perm`** — and the composite `ω ↦ −(ω ∘ θ)`, in one line from the general
theorem. **`negPerm_ne_permField`** and **`negPerm_ne_neg`** prove it is in **neither** family: it
is `permField ψ` for no `ψ` at all (they disagree at the all-ones vector, which every `permField`
fixes), and it is not `ω ↦ −ω` unless `θ` is the identity (they disagree at a basis vector). That is
the evidence the generalisation is not a re-packaging: it produces a symmetry the estate could not
previously state, and the fact is proved rather than asserted.

**`quadForm_preserving_comp`** — the maps satisfying the hypothesis are closed under composition, so
the invariant isometries form a group; the three results above are members of it.

## What is NOT here

**No new symmetry of any named graph.** The general theorem says *if* an isometry preserves the
form *then* the measure is invariant. Producing isometries beyond permutations, signs and their
composites — a rotation inside a degenerate eigenspace of `green`, say, which
`TorusFibreOrbitPartition` shows the torus has in abundance — is **not attempted**, and what would
be needed is named rather than costed: an explicit orthogonal map preserving the eigenspace
decomposition. **No cost is claimed** (`ERRATUM 246`).

> ⚠ **PARTLY SUPERSEDED THE NEXT UNIT, AND KEPT AS WRITTEN** (`ERRATUM 94`, **`ERRATUM 453`**,
> 2026-09-04). `FieldSignFlip` exhibits one — **flip the field's sign on one connected component
> and leave the others alone** — and it needs **no eigenspace machinery whatever**, only
> `GreenDisconnected.green_eq_zero_of_not_reachable`. The paragraph above named *a rotation inside a
> degenerate eigenspace* as what would be needed; that is what is needed **on a connected graph**,
> and `FieldSignFlip.closed_iff_of_preconnected` proves the sign-flip route reaches no further. So
> the sentence is right about the hard case and wrong that the hard case was the only one — it named
> a **route** where `ERRATUM 452`, one unit earlier, had just established the rule to name a
> **statement**.

**Not a statement about the automorphism group.** `IsGraphAut` and the invariant isometries are
different objects: one lives on `V`, the other on `EuclideanSpace ℝ V`, and `permField` is the map
between them. Nothing here says the second is generated by the first.

**Not OS3, and not any OS axiom.** `FieldAutInvariance`'s header says in capitals that its statement
is the finite-volume shadow of a continuum axiom and not the axiom; **this file makes the same
disclaimer for a wider class of maps**, which is a wider shadow and not a smaller gap.

**No wall moves. No published tag moves.**

Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

namespace FieldIsometryInvariance

open Matrix GraphLaplacian MeasureTheory ProbabilityTheory FieldAutInvariance

variable {V : Type*} [Fintype V] [DecidableEq V] {G : SimpleGraph V} [DecidableRel G.Adj] {m : ℝ}

/-- The property that does all the work: `T`'s inverse preserves the propagator's quadratic form. -/
def PreservesQuadForm (G : SimpleGraph V) [DecidableRel G.Adj] (m : ℝ)
    (T : EuclideanSpace ℝ V ≃ₗᵢ[ℝ] EuclideanSpace ℝ V) : Prop :=
  ∀ t : EuclideanSpace ℝ V,
    (T.symm t) ⬝ᵥ (green G m *ᵥ (T.symm t)) = t ⬝ᵥ (green G m *ᵥ t)

/-! ## 1. The general theorem -/

/-- **THE GAUSSIAN FIELD IS INVARIANT UNDER EVERY ISOMETRY THAT PRESERVES THE COVARIANCE FORM.**
`gaussianField_map_perm` and `gaussianField_map_neg` are the two instances the estate had, and
their proofs differ from each other only in this hypothesis. -/
theorem gaussianField_map_isometry (hm : m ≠ 0)
    {T : EuclideanSpace ℝ V ≃ₗᵢ[ℝ] EuclideanSpace ℝ V} (hT : PreservesQuadForm G m T) :
    (gaussianField G m).map T = gaussianField G m := by
  have hps : (green G m).PosSemidef := (green_posDef G hm).posSemidef
  refine Measure.ext_of_charFun (funext fun t => ?_)
  rw [charFun_map_isometry, gaussianField, charFun_multivariateGaussian hps,
    charFun_multivariateGaussian hps, hT t]
  simp

/-- The invariant isometries are closed under composition, so they form a group. -/
theorem quadForm_preserving_comp {T U : EuclideanSpace ℝ V ≃ₗᵢ[ℝ] EuclideanSpace ℝ V}
    (hT : PreservesQuadForm G m T) (hU : PreservesQuadForm G m U) :
    PreservesQuadForm G m (T.trans U) := by
  intro t
  rw [show (T.trans U).symm t = T.symm (U.symm t) from rfl, hT (U.symm t), hU t]

/-! ## 2. The estate's two statements are instances -/

/-- A graph automorphism preserves the form — `FieldAutInvariance.green_quadForm_perm`. -/
theorem preservesQuadForm_permField {θ : V ≃ V} (hθ : IsGraphAut G θ) (m : ℝ) :
    PreservesQuadForm G m (permField θ) :=
  fun t => green_quadForm_perm hθ m t

/-- **`gaussianField_map_perm`, FROM THE GENERAL THEOREM.** The original stays as written. -/
theorem gaussianField_map_perm' {θ : V ≃ V} (hθ : IsGraphAut G θ) (hm : m ≠ 0) :
    (gaussianField G m).map (permField θ) = gaussianField G m :=
  gaussianField_map_isometry hm (preservesQuadForm_permField hθ m)

/-- `ω ↦ −ω` preserves the form, because the form is quadratic. -/
theorem preservesQuadForm_neg (G : SimpleGraph V) [DecidableRel G.Adj] (m : ℝ) :
    PreservesQuadForm G m (LinearIsometryEquiv.neg ℝ) := by
  intro t
  change ((-t : EuclideanSpace ℝ V)) ⬝ᵥ (green G m *ᵥ ((-t : EuclideanSpace ℝ V)))
    = t ⬝ᵥ (green G m *ᵥ t)
  rw [WithLp.ofLp_neg, Matrix.mulVec_neg, dotProduct_neg, neg_dotProduct, neg_neg]

/-- **`gaussianField_map_neg`, FROM THE GENERAL THEOREM.** The original stays as written. -/
theorem gaussianField_map_neg' (hm : m ≠ 0) :
    (gaussianField G m).map (LinearIsometryEquiv.neg ℝ) = gaussianField G m :=
  gaussianField_map_isometry hm (preservesQuadForm_neg G m)

/-! ## 3. And a symmetry in neither family -/

/-- **`ω ↦ −(ω ∘ θ)` IS A SYMMETRY OF THE FIELD**, for every graph automorphism `θ`. It is not a
`permField` and not `±id`; it is the composite, and it costs one line because the hypothesis is
closed under composition. -/
theorem gaussianField_map_neg_perm {θ : V ≃ V} (hθ : IsGraphAut G θ) (hm : m ≠ 0) :
    (gaussianField G m).map ((permField θ).trans (LinearIsometryEquiv.neg ℝ))
      = gaussianField G m :=
  gaussianField_map_isometry hm
    (quadForm_preserving_comp (preservesQuadForm_permField hθ m) (preservesQuadForm_neg G m))

omit [DecidableEq V] in
/-- Every `permField` fixes the all-ones vector. -/
theorem permField_one (ψ : V ≃ V) :
    permField ψ (WithLp.toLp 2 (fun _ : V => (1 : ℝ)) : EuclideanSpace ℝ V)
      = WithLp.toLp 2 (fun _ : V => (1 : ℝ)) := by
  ext p
  rw [permField_apply]

omit [DecidableEq V] in
/-- **THE COMPOSITE IS NOT A PERMUTATION OF SITES**, for any `ψ` whatever: it sends the all-ones
vector to its negative, and every `permField` fixes it. -/
theorem negPerm_ne_permField [Nonempty V] (θ ψ : V ≃ V) :
    (permField θ).trans (LinearIsometryEquiv.neg ℝ) ≠ permField ψ := by
  intro hcontra
  have h := DFunLike.congr_fun hcontra
    (WithLp.toLp 2 (fun _ : V => (1 : ℝ)) : EuclideanSpace ℝ V)
  have hleft : ((permField θ).trans (LinearIsometryEquiv.neg ℝ))
      (WithLp.toLp 2 (fun _ : V => (1 : ℝ)) : EuclideanSpace ℝ V)
      = -(permField θ (WithLp.toLp 2 (fun _ : V => (1 : ℝ)) : EuclideanSpace ℝ V)) := rfl
  rw [hleft, permField_one θ, permField_one ψ] at h
  have hval := congrFun (congrArg (fun x : EuclideanSpace ℝ V => WithLp.ofLp x) h)
    (Classical.arbitrary V)
  norm_num at hval

/-- A permutation acts on a basis vector by moving its support. -/
theorem permField_single (ψ : V ≃ V) (p : V) :
    permField ψ (WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V)
      = WithLp.toLp 2 (Pi.single (ψ p) (1 : ℝ)) := by
  ext q
  rw [permField_apply]
  simp [Pi.single_apply, Equiv.symm_apply_eq]

omit [DecidableEq V] in
/-- **AND IT IS NOT `ω ↦ −ω`** unless `θ` is the identity. -/
theorem negPerm_ne_neg {θ : V ≃ V} (hθ : θ ≠ Equiv.refl V) :
    (permField θ).trans (LinearIsometryEquiv.neg ℝ) ≠ LinearIsometryEquiv.neg ℝ := by
  classical
  intro hcontra
  refine hθ (Equiv.ext fun p => ?_)
  change θ p = p
  have h := DFunLike.congr_fun hcontra
    (WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V)
  have hleft : ((permField θ).trans (LinearIsometryEquiv.neg ℝ))
      (WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V)
      = -(permField θ (WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V)) := rfl
  have hright : (LinearIsometryEquiv.neg ℝ)
      (WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V)
      = -(WithLp.toLp 2 (Pi.single p (1 : ℝ)) : EuclideanSpace ℝ V) := rfl
  rw [hleft, hright, neg_inj, permField_single θ p] at h
  have hval := congrFun (congrArg (fun x : EuclideanSpace ℝ V => WithLp.ofLp x) h) (θ p)
  dsimp only at hval
  by_cases hpp : θ p = p
  · exact hpp
  · rw [Pi.single_eq_same, Pi.single_eq_of_ne hpp] at hval
    norm_num at hval

end FieldIsometryInvariance
