/-
  FiniteStone: Stone's Theorem in the Bounded Case — Schrödinger Evolution
  ========================================================================

  Upgrades: the Stone (1932) citation in QuantumLineage/tree §8, previously
  prose-only. The published tag for "Schrödinger via Stone" is [PREDICTED].

  WHAT THIS FILE PROVES (exactly this, nothing more):

  For a self-adjoint element H of ANY unital C⋆-algebra-like A (normed ring,
  ℂ-algebra, complete, star structure) — in particular for every finite
  cascade level Mₙ(ℂ) and every bounded Hamiltonian:

  1. `unitaryGroup H : ℝ → unitary A`, t ↦ exp(itH) — each value genuinely a
     member of the unitary group (inherited from `selfAdjoint.expUnitary`).
  2. `unitaryGroup_zero`, `unitaryGroup_add` — U(0) = 1 and
     U(s+t) = U(s)·U(t): a genuine one-parameter group homomorphism.
  3. `unitaryGroup_neg_mul`, `unitaryGroup_star` — U(t)·U(−t) = 1 and
     U(t)* = U(−t): inverses are adjoints (unitarity in equation form).
  4. `continuous_unitaryGroup` — t ↦ U(t) is continuous.
  5. `hasDerivAt_unitaryGroup` — dU/dt = (iH)·U(t) for every t: the abstract
     Schrödinger equation at operator level, with derivative in the norm
     topology of A.
  6. `generator_recovery`, `generator_determined` — dU/dt|₀ = iH, hence
     H = −i·(dU/dt|₀): the group determines its generator.
  7. `schrodinger_equation` — on any complex Hilbert space E and bounded
     self-adjoint H : E →L[ℂ] E, for every state ψ:
     d/dt (U(t)ψ) = (iH)(U(t)ψ). The Schrödinger equation for states.
  8. `cascade_schrodinger` — the same, instantiated at EuclideanSpace ℂ (Fin n)
     for every n: every finite cascade level satisfies the Schrödinger
     equation. (n = 4 is the cascade's M₄ level acting on ℂ⁴.)

  NOT proven here (stated to keep the tag honest): the genuinely
  infinite-dimensional Stone theorem — that every STRONGLY CONTINUOUS
  one-parameter unitary group has a densely defined (generally UNBOUNDED)
  self-adjoint generator — requires unbounded-operator spectral theory absent
  from Mathlib; it remains open here. This file is the complete bounded case:
  forward direction, group laws, and generator recovery. For the cascade's
  finite levels the bounded case is the whole story.

  Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

import Mathlib.Analysis.CStarAlgebra.Exponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Comp
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.LinearAlgebra.Complex.Module

open Complex NormedSpace selfAdjoint

noncomputable section

namespace FiniteStone

variable {A : Type*} [NormedRing A] [StarRing A] [NormedAlgebra ℂ A]
  [CompleteSpace A] [StarModule ℂ A] [ContinuousStar A]

/-! ## 1. The one-parameter unitary group of a bounded self-adjoint element -/

/-- The one-parameter unitary group generated by a self-adjoint element:
    `U(t) = exp(i·t·H)`, valued in the unitary group of `A`. -/
def unitaryGroup (H : selfAdjoint A) (t : ℝ) : unitary A :=
  expUnitary (t • H)

/-- The underlying element: `U(t) = exp(t • (i•H))` as a member of `A`. -/
theorem unitaryGroup_coe (H : selfAdjoint A) (t : ℝ) :
    ((unitaryGroup H t : unitary A) : A) = exp (t • (I • (H : A))) := by
  rw [unitaryGroup, expUnitary_coe]
  congr 1
  exact smul_comm I t (H : A)

/-- U(0) = 1. -/
theorem unitaryGroup_zero (H : selfAdjoint A) : unitaryGroup H 0 = 1 := by
  rw [unitaryGroup, zero_smul, expUnitary_zero]

/-- The group law U(s+t) = U(s)·U(t): a genuine homomorphism (ℝ,+) → unitary A. -/
theorem unitaryGroup_add (H : selfAdjoint A) (s t : ℝ) :
    unitaryGroup H (s + t) = unitaryGroup H s * unitaryGroup H t := by
  rw [unitaryGroup, unitaryGroup, unitaryGroup, add_smul]
  exact Commute.expUnitary_add (((Commute.refl (H : A)).smul_left s).smul_right t)

/-- U(t)·U(−t) = 1: pointwise inverses inside the unitary group. -/
theorem unitaryGroup_neg_mul (H : selfAdjoint A) (t : ℝ) :
    unitaryGroup H t * unitaryGroup H (-t) = 1 := by
  rw [← unitaryGroup_add, add_neg_cancel, unitaryGroup_zero]

/-- U(t)* = U(−t): the adjoint reverses time. In the unitary group star is
    inversion (`Unitary.star_eq_inv`), and U(−t) is the inverse of U(t) by the
    group law. -/
theorem unitaryGroup_star (H : selfAdjoint A) (t : ℝ) :
    star (unitaryGroup H t) = unitaryGroup H (-t) := by
  rw [Unitary.star_eq_inv]
  exact inv_eq_of_mul_eq_one_right (unitaryGroup_neg_mul H t)

/-- Continuity of t ↦ U(t). -/
theorem continuous_unitaryGroup (H : selfAdjoint A) :
    Continuous (unitaryGroup H) := by
  apply selfAdjoint.continuous_expUnitary.comp
  have : Continuous fun t : ℝ => t • (H : A) :=
    continuous_id.smul continuous_const
  exact Continuous.subtype_mk this _

/-! ## 2. The Schrödinger equation at operator level, and generator recovery -/

/-- **The abstract Schrödinger equation**: dU/dt = (iH)·U(t), with the
    derivative in the norm topology of A. Proven from Mathlib's
    `hasDerivAt_exp_smul_const'` after rewriting U(t) = exp(t • (iH)). -/
theorem hasDerivAt_unitaryGroup (H : selfAdjoint A) (t : ℝ) :
    HasDerivAt (fun s => ((unitaryGroup H s : unitary A) : A))
      ((I • (H : A)) * ((unitaryGroup H t : unitary A) : A)) t := by
  simp_rw [unitaryGroup_coe]
  exact hasDerivAt_exp_smul_const' (I • (H : A)) t

/-- Generator recovery: dU/dt at t = 0 is exactly iH. -/
theorem generator_recovery (H : selfAdjoint A) :
    HasDerivAt (fun s => ((unitaryGroup H s : unitary A) : A)) (I • (H : A)) 0 := by
  have h := hasDerivAt_unitaryGroup H 0
  rwa [unitaryGroup_zero, OneMemClass.coe_one, mul_one] at h

omit [CompleteSpace A] [StarModule ℂ A] [ContinuousStar A] in
/-- The group determines its generator: H = −i·(dU/dt|₀). Together with
    `generator_recovery` this is the bounded-case content of Stone's
    correspondence H ↔ U in both directions for the groups constructed here. -/
theorem generator_determined (H : selfAdjoint A) :
    (-I) • (I • (H : A)) = (H : A) := by
  rw [smul_smul, neg_mul, Complex.I_mul_I, neg_neg, one_smul]

/-! ## 3. The Schrödinger equation for states on a Hilbert space -/

/-- Evaluation at a fixed vector, as a continuous ℝ-linear map on operators.
    (Self-contained; avoids needing the ℝ/ℂ scalar-tower instance on E.) -/
def evalCLM {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] (ψ : E) :
    (E →L[ℂ] E) →L[ℝ] E :=
  LinearMap.mkContinuous
    { toFun := fun T => T ψ
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
    ‖ψ‖ (fun T => by rw [mul_comm]; exact T.le_opNorm ψ)

@[simp]
theorem evalCLM_apply {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
    (ψ : E) (T : E →L[ℂ] E) : evalCLM ψ T = T ψ := rfl

/-- **The Schrödinger equation**: for a bounded self-adjoint Hamiltonian H on
    a complex Hilbert space E and any state ψ,
    `d/dt (U(t)ψ) = (iH)(U(t)ψ)`. -/
theorem schrodinger_equation {E : Type*} [NormedAddCommGroup E]
    [InnerProductSpace ℂ E] [CompleteSpace E]
    (H : selfAdjoint (E →L[ℂ] E)) (ψ : E) (t : ℝ) :
    HasDerivAt (fun s => ((unitaryGroup H s : unitary (E →L[ℂ] E)) : E →L[ℂ] E) ψ)
      (((I • (H : E →L[ℂ] E)) *
        ((unitaryGroup H t : unitary (E →L[ℂ] E)) : E →L[ℂ] E)) ψ) t := by
  have hop := hasDerivAt_unitaryGroup H t
  simpa using HasFDerivAt.comp_hasDerivAt t ((evalCLM ψ).hasFDerivAt) hop

/-- **Every finite cascade level satisfies the Schrödinger equation.** The
    instantiation E := ℂⁿ (EuclideanSpace) covers the cascade algebras Mₙ(ℂ)
    acting on their natural Hilbert spaces — n = 2 the seed, n = 4 the
    spacetime level, and every deeper level. -/
theorem cascade_schrodinger (n : ℕ)
    (H : selfAdjoint (EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n)))
    (ψ : EuclideanSpace ℂ (Fin n)) (t : ℝ) :
    HasDerivAt
      (fun s => ((unitaryGroup H s :
        unitary (EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n))) :
        EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n)) ψ)
      (((I • (H : EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n))) *
        ((unitaryGroup H t :
          unitary (EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n))) :
          EuclideanSpace ℂ (Fin n) →L[ℂ] EuclideanSpace ℂ (Fin n))) ψ) t :=
  schrodinger_equation H ψ t

end FiniteStone
