import TorusTranslation

/-!
# The automorphisms form a group, and the lattice's point group is inside it

`FieldAutInvariance.gaussianField_map_perm` proves the Gaussian field invariant under **every**
graph automorphism. The `UNLOCK_WATCHLIST` item that recorded it also recorded, twice, what was
wrong with the way it sits in the estate:

> **HONEST WEAKNESS:** the hypothesis was weakened from involutive reflections to arbitrary
> automorphisms and **the estate constructs no non-involutive automorphism** … A promise until
> one is built.

and, after `TorusTranslation` discharged that half:

> **STILL ABSENT:** coordinate permutations of the `d` axes, automorphisms of both box and torus,
> **built nowhere and consumed by nothing.**

This file closes the second sentence. But the first one points at something the estate had not
noticed, and it is the more useful half.

## The structural gap: exhibiting examples was never the right fix

`IsGraphAut` is a bare `Prop` with one constructor, `of_isRefl`, and — counted rather than
recalled — **exactly one statement in the whole estate that does not go through it**:
`TorusTranslation.isGraphAut_shift`. Everything else the estate can hand to
`gaussianField_map_perm` is an involution arriving via `of_isRefl`, of which there are many.
**And nothing said the automorphisms compose.** So every new symmetry had to be built and proved
from the adjacency relation by hand, and the answer to *"the estate constructs too few
automorphisms"* looked like *"construct more."*

It is not. §1 makes `IsGraphAut G` a **`Subgroup (Equiv.Perm V)`**, which is three one-line
obligations, and after that **generators suffice**: `gaussianField_invariant_closure` says the
field is invariant under everything in the subgroup generated by any set of automorphisms, so a
symmetry group is exhibited by naming its generators and never again by naming its elements.

## What that then buys, in the case the item asked for

§3 builds the missing coordinate permutations — once, generically, because `boxGraph` and
`torusGraph` share both the vertex type and the shape *"agree off one axis, and on that axis
stand in relation `P`"*. Proving it twice would be proving it once and copying it.

§4 is the payoff. With the axis reversals `revSite i` already in the estate and the axis
permutations now beside them, §1 hands over the whole subgroup they generate, and the Gaussian
field is invariant under every element of it — on the box and on the torus, at every side length,
dimension and nonzero mass, with no element ever written down. On the torus the translations join
the generating set and the group grows accordingly.

**What that subgroup is called, and what is actually proved.** Those generators are the natural
action of the **signed permutations of the `d` axes** — the hyperoctahedral group, the point group
of the cubic lattice. What §4 proves is the containment
`Subgroup.closure (pointGens d n) ≤ graphAut`, and **not** that the closure is isomorphic to
`(ℤ/2)^d ⋊ S_d`. That identification is not formalised here, is not needed by anything below, and
should not be read into the theorem names. §5 does the minimum that keeps the containment from
being empty talk: the two families are **distinct** (`permSite_ne_revSite`) and the group is
**not** a group of involutions (`permSite_not_involutive`), so §1's algebra is doing work that
`GraphReflection.IsRefl` — which carries involutivity as a structure field — could not.

## What this is not, stated because the neighbouring item was misread once already

**It is not OS3**, and no theorem here should be recorded as OS3. OS3 is invariance under the
Euclidean group `E(d)`, which is continuous and infinite; the hyperoctahedral group is finite, the
box has no translations at all, and the torus's are a finite cyclic group per axis. What is true
is narrower and worth having on its own terms: **the estate can now name the full point group of
its lattice, and the field is invariant under it** — where before it could name two elements.

Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

namespace LatticePointGroup

open BoxGraph TorusReflection FieldAutInvariance

/-! ## 1. The automorphisms are a subgroup

Three obligations, none longer than a line. Recorded as a `Subgroup` rather than as three lemmas
because the point is the closure property, and a `Subgroup` is what `Subgroup.closure_le` consumes.
-/

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- **THE AUTOMORPHISM GROUP.** `FieldAutInvariance.IsGraphAut` was a predicate with no algebra;
this is the same predicate with the algebra it always had. -/
def graphAut (G : SimpleGraph V) : Subgroup (Equiv.Perm V) where
  carrier := {θ | IsGraphAut G θ}
  one_mem' := fun _ _ => Iff.rfl
  mul_mem' {θ ρ} hθ hρ := fun p q => by
    simp only [Equiv.Perm.mul_apply]
    exact (hθ (ρ p) (ρ q)).trans (hρ p q)
  inv_mem' {θ} hθ := fun p q => by
    have := hθ (θ⁻¹ p) (θ⁻¹ q)
    simpa using this.symm

omit [Fintype V] [DecidableEq V] in
theorem mem_graphAut {G : SimpleGraph V} {θ : Equiv.Perm V} :
    θ ∈ graphAut G ↔ IsGraphAut G θ := Iff.rfl

/-! ## 2. So a symmetry group is exhibited by its generators

This is the lemma the estate was missing. It turns *"build another automorphism"* into *"name the
generators once"*, and it is `Subgroup.closure_le` with the field-invariance theorem attached.
-/

variable {G : SimpleGraph V} [DecidableRel G.Adj]

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
/-- **EVERYTHING GENERATED BY AUTOMORPHISMS IS AN AUTOMORPHISM.** -/
theorem closure_le_graphAut {S : Set (Equiv.Perm V)} (hS : ∀ θ ∈ S, IsGraphAut G θ) :
    Subgroup.closure S ≤ graphAut G :=
  Subgroup.closure_le _ |>.mpr hS

/-- **AND SO THE FIELD IS INVARIANT UNDER THE WHOLE GROUP THEY GENERATE.** No element of it is ever
built, named or fed to the adjacency relation. -/
theorem gaussianField_invariant_closure {S : Set (Equiv.Perm V)} (hS : ∀ θ ∈ S, IsGraphAut G θ)
    {m : ℝ} (hm : m ≠ 0) {θ : Equiv.Perm V} (hθ : θ ∈ Subgroup.closure S) :
    (GraphLaplacian.gaussianField G m).map (permField θ)
      = GraphLaplacian.gaussianField G m :=
  gaussianField_map_perm (closure_le_graphAut hS hθ) hm

/-! ## 3. The coordinate permutations, built once for both graphs

`boxGraph` and `torusGraph` share the vertex type `Fin d → Fin n` and share the shape of their
adjacency: *agree off one axis, and on that axis stand in some relation*. Only the relation differs
— a step for the box, a step-or-wrap for the torus. §3 permutes the axes against an arbitrary
relation, so each graph is one instantiation and neither proof is a copy of the other.
-/

variable {d n : ℕ}

/-- Permuting the axes of a site. -/
def permSite (π : Equiv.Perm (Fin d)) : Site d n ≃ Site d n where
  toFun p := fun j => p (π j)
  invFun p := fun j => p (π.symm j)
  left_inv p := by funext j; simp
  right_inv p := by funext j; simp

@[simp] theorem permSite_apply (π : Equiv.Perm (Fin d)) (p : Site d n) (j : Fin d) :
    permSite π p j = p (π j) := rfl

/-- **THE AXIS-LOCAL SHAPE IS PERMUTATION INVARIANT**, for any relation on the axis. The box and
the torus differ only in `P`, so this is proved once. -/
theorem exists_axis_perm (π : Equiv.Perm (Fin d)) (P : Fin n → Fin n → Prop) (p q : Site d n) :
    (∃ i : Fin d, (∀ j, j ≠ i → permSite π p j = permSite π q j)
        ∧ P (permSite π p i) (permSite π q i))
      ↔ ∃ i : Fin d, (∀ j, j ≠ i → p j = q j) ∧ P (p i) (q i) := by
  simp only [permSite_apply]
  constructor
  · rintro ⟨i, hsame, hstep⟩
    refine ⟨π i, fun j hj => ?_, hstep⟩
    have hj' : π.symm j ≠ i := fun hc => hj (by rw [← hc, Equiv.apply_symm_apply])
    have := hsame (π.symm j) hj'
    rwa [Equiv.apply_symm_apply] at this
  · rintro ⟨i, hsame, hstep⟩
    refine ⟨π.symm i, fun j hj => ?_, ?_⟩
    · exact hsame (π j) fun hc => hj (by rw [← Equiv.symm_apply_apply π j, hc])
    · rwa [Equiv.apply_symm_apply]

/-- **AN AXIS PERMUTATION IS AN AUTOMORPHISM OF THE BOX**, at every dimension and side. -/
theorem isGraphAut_permSite_box (π : Equiv.Perm (Fin d)) :
    IsGraphAut (boxGraph d n) (permSite π) := fun p q =>
  exists_axis_perm π (fun a b => a.val + 1 = b.val ∨ b.val + 1 = a.val) p q

/-- **AND OF THE TORUS.** Same proof, different relation on the axis. -/
theorem isGraphAut_permSite_torus (π : Equiv.Perm (Fin d)) :
    IsGraphAut (torusGraph d n) (permSite π) := fun p q =>
  exists_axis_perm π adjT p q

/-- **SO THE FIELD IS INVARIANT UNDER PERMUTING THE AXES**, on the box. -/
theorem gaussianField_map_permSite_box (π : Equiv.Perm (Fin d)) {m : ℝ} (hm : m ≠ 0) :
    (GraphLaplacian.gaussianField (boxGraph d n) m).map (permField (permSite π))
      = GraphLaplacian.gaussianField (boxGraph d n) m :=
  gaussianField_map_perm (isGraphAut_permSite_box π) hm

/-- **AND ON THE TORUS.** -/
theorem gaussianField_map_permSite_torus (π : Equiv.Perm (Fin d)) {m : ℝ} (hm : m ≠ 0) :
    (GraphLaplacian.gaussianField (torusGraph d n) m).map (permField (permSite π))
      = GraphLaplacian.gaussianField (torusGraph d n) m :=
  gaussianField_map_perm (isGraphAut_permSite_torus π) hm

/-! ## 4. The point group

Axis reversals were already in the estate; axis permutations are now beside them. §1 says the two
families generate a group without anything being composed by hand, and §2 says the field is
invariant under all of it. That group is the **signed permutations of the `d` axes** — the
hyperoctahedral group, the point group of the cubic lattice.
-/

/-- The generators: reverse any one axis, or permute the axes. -/
def pointGens (d n : ℕ) : Set (Equiv.Perm (Site d n)) :=
  {θ | (∃ i : Fin d, θ = GraphReflection.revSite (n := n) i)
        ∨ ∃ π : Equiv.Perm (Fin d), θ = permSite π}

/-- **THE POINT GROUP OF THE BOX.** Every signed permutation of the axes is an automorphism, and
none of them had to be written down. -/
theorem pointGroup_le_graphAut_box :
    Subgroup.closure (pointGens d n) ≤ graphAut (boxGraph d n) := by
  refine closure_le_graphAut ?_
  rintro θ (⟨i, rfl⟩ | ⟨π, rfl⟩)
  · exact IsGraphAut.of_isRefl (GraphReflection.boxGraph_revSite_aut i)
  · exact isGraphAut_permSite_box π

/-- **AND OF THE TORUS**, where the translations join them. -/
theorem pointGroup_le_graphAut_torus [NeZero n] :
    Subgroup.closure (pointGens d n ∪ {θ | ∃ i k, θ = TorusTranslation.shift (n := n) i k})
      ≤ graphAut (torusGraph d n) := by
  refine closure_le_graphAut ?_
  rintro θ ((⟨i, rfl⟩ | ⟨π, rfl⟩) | ⟨i, k, rfl⟩)
  · exact IsGraphAut.of_isRefl (TorusReflection.isRefl_torus i)
  · exact isGraphAut_permSite_torus π
  · exact TorusTranslation.isGraphAut_shift i k

/-- **THE GAUSSIAN FIELD IS INVARIANT UNDER THE WHOLE POINT GROUP OF THE BOX.** -/
theorem gaussianField_invariant_pointGroup_box {m : ℝ} (hm : m ≠ 0)
    {θ : Equiv.Perm (Site d n)} (hθ : θ ∈ Subgroup.closure (pointGens d n)) :
    (GraphLaplacian.gaussianField (boxGraph d n) m).map (permField θ)
      = GraphLaplacian.gaussianField (boxGraph d n) m :=
  gaussianField_map_perm (pointGroup_le_graphAut_box hθ) hm

/-- **AND UNDER THE POINT GROUP TOGETHER WITH THE TRANSLATIONS, ON THE TORUS.** -/
theorem gaussianField_invariant_pointGroup_torus [NeZero n] {m : ℝ} (hm : m ≠ 0)
    {θ : Equiv.Perm (Site d n)}
    (hθ : θ ∈ Subgroup.closure
      (pointGens d n ∪ {θ | ∃ i k, θ = TorusTranslation.shift (n := n) i k})) :
    (GraphLaplacian.gaussianField (torusGraph d n) m).map (permField θ)
      = GraphLaplacian.gaussianField (torusGraph d n) m :=
  gaussianField_map_perm (pointGroup_le_graphAut_torus hθ) hm

/-! ## 5. The group is not trivial, and the generality is exercised

`TorusTranslation` discharged its promise by exhibiting a non-involutive automorphism, on the
grounds that a weakened hypothesis nothing exercises is a promise. The same standard applies here:
a subgroup generated by two families is worth nothing if the families coincide or are trivial.
-/

/-- **AXIS PERMUTATIONS ARE NOT AXIS REVERSALS**, so §4's two families are genuinely two. At `d = 2`
the swap moves a site that every reversal of the first axis fixes. -/
theorem permSite_ne_revSite :
    permSite (n := 3) (Equiv.swap (0 : Fin 2) 1) ≠ GraphReflection.revSite (n := 3) 0 := by
  intro hc
  have h := congrFun (Equiv.ext_iff.mp hc ![0, 1]) 0
  revert h
  decide

/-- **AND THE PERMUTATIONS ARE NOT INVOLUTIVE IN GENERAL**, so §1's group structure is doing work
that `IsRefl` could not reach: a three-cycle of axes is an automorphism of order three, and
`GraphReflection.IsRefl` carries involutivity as a structure field. -/
theorem permSite_not_involutive :
    ¬ ∀ p : Site 3 2, permSite (Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2)
        (permSite (Equiv.swap (0 : Fin 3) 1 * Equiv.swap 1 2) p) = p := by
  intro hinv
  have h := congrFun (hinv ![0, 1, 1]) 0
  revert h
  decide

end LatticePointGroup
