/-
  LorentzGroup: O(1,3) as a Bundled Group, and Where SL₂(ℂ) Lands In It
  ====================================================================

  Campaign-3 unit 2, steps (i) and (ii) of the staircase that
  `MinkowskiSignature.lean` wrote down for itself.

  That file proved the SL₂(ℂ) conjugation action on Herm₂(ℂ), read in Pauli
  coordinates, is an ℝ-linear self-map of ℝ⁴ preserving the Minkowski form,
  and then said what was still missing: "(i) exhibit the image inside the
  orthogonal group of `minkowskiForm` as a bundled object; (ii) define the
  orthochronous and proper conditions (Λ⁰₀ > 0 and det = 1) — Mathlib has no
  Lorentz group; (iii) surjectivity itself."

  This file does (i) and (ii). Step (iii) is still open and is discussed at
  the end.

  WHAT THIS FILE PROVES (exactly this, nothing more):

  1. `O13` — **the Lorentz group O(1,3) as a genuine `Subgroup` of GL₄(ℝ)**,
     carrier {Λ : Λᵀ G Λ = G} for G = diag(1,−1,−1,−1). Closed under
     multiplication and inverse, so it is a group and not merely a set.
  2. `lorentzMat_mul`, `lorentzMat_one` — the SL₂(ℂ) action is
     **multiplicative**: Λ(AB) = Λ(A)Λ(B), Λ(1) = 1. This is the fact that
     makes it a homomorphism rather than a family of maps, and it is what
     everything downstream (properness by squares, the group structure of the
     image) rests on.
  3. `lorentzMat_gram` — Λ(A)ᵀ G Λ(A) = G: the image lies in O(1,3), now at
     the level of matrices, which is what a determinant argument needs.
  4. `lorentzUnit`, `lorentzUnit_mem_O13` — the image as elements of the
     bundled subgroup, and `lorentzHom` bundling it as a `MonoidHom` from
     SL₂(ℂ) to O(1,3). Step (i), done.
  5. `det_lorentzMat_sq` — det Λ(A)² = 1 for any isometry; then
     **`det_lorentzMat` — det Λ(A) = +1: the image is PROPER.** The proof is
     not the usual connectedness argument: `exists_sqrt_of_trace_ne`
     constructs a square root N of A inside SL₂(ℂ) explicitly, by
     N = (A + 1)/√(tr A + 2) — legitimate exactly when tr A ≠ −2 — and when
     tr A = −2 uses A = (J·J)·(N·N) with J = [[0,−1],[1,0]], N² = −A. So
     every A ∈ SL₂(ℂ) is a product of squares, det Λ is multiplicative, and a
     square of ±1 is +1. This is elementary and needs no topology.
  6. `lorentzMat_zero_zero` — Λ(A)⁰₀ = ½(|a|²+|b|²+|c|²+|d|²), and
     **`one_le_lorentzMat_zero_zero` — Λ(A)⁰₀ ≥ 1 > 0: the image is
     ORTHOCHRONOUS**, from |ad − bc| = 1 and AM–GM. Step (ii), done, and
     with a sharp constant: 1 is attained (`lorentzMat_one`).
  7. `SOplus13` — **the proper orthochronous Lorentz group SO⁺(1,3) as a
     `Subgroup`**. The non-obvious closure is orthochronicity: (ΛΛ′)⁰₀ > 0
     needs a Cauchy–Schwarz argument (`orthochronous_mul`) on the space
     directions, proved here from the Lagrange identity.
  8. `lorentzHom_mem_SOplus` — **the image of SL₂(ℂ) lies in SO⁺(1,3)**, and
     `lorentzSOplusHom`, the bundled `MonoidHom` SL₂(ℂ) →* SO⁺(1,3), whose
     kernel is {±1} by `MinkowskiHerm2.kernel_of_conj_action`.

  NOT proven here — and this is the whole of what remains of old gap #7:

  * **SURJECTIVITY** of SL₂(ℂ) → SO⁺(1,3). Everything above says the image is
    a subgroup of SO⁺(1,3) with kernel {±1}; nothing above says it is all of
    it. The classical proof needs SO⁺(1,3) to be generated by rotations and
    boosts and needs SU(2) ↠ SO(3); neither is in Mathlib and neither is a
    corollary of anything here. The remaining leg is recorded on
    `UNLOCK_WATCHLIST.md`.
  * That SO⁺(1,3) is the identity component (a topological statement; the
    definition used here is the algebraic one, det = 1 and Λ⁰₀ > 0, which is
    equivalent but not proven equivalent here).
  * Any identification of SL₂(ℂ) with Mathlib's `spinGroup`.

  Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

import MinkowskiSignature
import Mathlib.Analysis.Complex.Polynomial.Basic

open Matrix MinkowskiHerm2 MinkowskiSignature

noncomputable section

namespace LorentzGroup

/-! ## 1. The Minkowski Gram matrix and its bilinear form

    `minkowskiForm` is a `QuadraticForm`; a determinant argument needs the
    matrix identity ΛᵀGΛ = G, so we need the associated bilinear form and
    its Gram matrix explicitly. -/

/-- The Gram matrix G = diag(1, −1, −1, −1) of the Minkowski form. -/
def gram : Matrix (Fin 4) (Fin 4) ℝ := Matrix.diagonal mw

@[simp] theorem gram_mul_gram : gram * gram = 1 := by
  rw [gram, Matrix.diagonal_mul_diagonal]
  rw [show (fun i => mw i * mw i) = fun _ : Fin 4 => (1 : ℝ) by
    funext i; fin_cases i <;> norm_num [mw]]
  exact Matrix.diagonal_one

theorem det_gram : gram.det = -1 := by
  rw [gram, Matrix.det_diagonal, Fin.prod_univ_four, show mw 0 = 1 from rfl,
    show mw 1 = -1 from rfl, show mw 2 = -1 from rfl, show mw 3 = -1 from rfl]
  norm_num

/-- The Minkowski bilinear form, written out. -/
def bil (v w : Fin 4 → ℝ) : ℝ :=
  v 0 * w 0 - v 1 * w 1 - v 2 * w 2 - v 3 * w 3

theorem bil_self (v : Fin 4 → ℝ) : bil v v = minkowskiForm v := by
  rw [minkowskiForm_apply, bil]; ring

/-- Polarisation: the quadratic form determines the bilinear form. -/
theorem polarization (v w : Fin 4 → ℝ) :
    minkowskiForm (v + w) = minkowskiForm v + minkowskiForm w + 2 * bil v w := by
  simp only [minkowskiForm_apply, bil, Pi.add_apply]; ring

/-! ## 2. The action is multiplicative

    This is the step that turns `lorentzLin` from a family of isometries into
    a group homomorphism. -/

theorem lorentzMap_mul (A B : Matrix (Fin 2) (Fin 2) ℂ) (v : Fin 4 → ℝ) :
    lorentzMap (A * B) v = lorentzMap A (lorentzMap B v) := by
  have hherm : (B * pauliHerm (v 0) (v 1) (v 2) (v 3) * Bᴴ)ᴴ
      = B * pauliHerm (v 0) (v 1) (v 2) (v 3) * Bᴴ :=
    conj_action_hermitian B _ (pauliHerm_isHermitian _ _ _ _)
  have hround := pauliHerm_pauliCoord _ hherm
  change pauliCoord ((A * B) * pauliHerm (v 0) (v 1) (v 2) (v 3) * (A * B)ᴴ)
      = pauliCoord (A * pauliHerm (lorentzMap B v 0) (lorentzMap B v 1)
          (lorentzMap B v 2) (lorentzMap B v 3) * Aᴴ)
  rw [show lorentzMap B v = pauliCoord (B * pauliHerm (v 0) (v 1) (v 2) (v 3) * Bᴴ)
      from rfl, hround]
  exact congrArg pauliCoord (conj_action_mul A B _)

theorem lorentzLin_mul (A B : Matrix (Fin 2) (Fin 2) ℂ) :
    lorentzLin (A * B) = (lorentzLin A) ∘ₗ (lorentzLin B) :=
  LinearMap.ext fun v => lorentzMap_mul A B v

theorem lorentzLin_one : lorentzLin (1 : Matrix (Fin 2) (Fin 2) ℂ) = LinearMap.id :=
  LinearMap.ext fun v => lorentzMap_one v

/-! ## 3. The Lorentz matrix -/

/-- **Λ(A)**: the 4×4 real matrix of the action of A ∈ SL₂(ℂ) on ℝ⁴. -/
def lorentzMat (A : Matrix (Fin 2) (Fin 2) ℂ) : Matrix (Fin 4) (Fin 4) ℝ :=
  LinearMap.toMatrix' (lorentzLin A)

theorem lorentzMat_mulVec (A : Matrix (Fin 2) (Fin 2) ℂ) (v : Fin 4 → ℝ) :
    lorentzMat A *ᵥ v = lorentzMap A v :=
  LinearMap.toMatrix'_mulVec (lorentzLin A) v

/-- **Λ is multiplicative.** -/
theorem lorentzMat_mul (A B : Matrix (Fin 2) (Fin 2) ℂ) :
    lorentzMat (A * B) = lorentzMat A * lorentzMat B := by
  rw [lorentzMat, lorentzLin_mul, LinearMap.toMatrix'_comp, lorentzMat, lorentzMat]

@[simp] theorem lorentzMat_one : lorentzMat (1 : Matrix (Fin 2) (Fin 2) ℂ) = 1 := by
  rw [lorentzMat, lorentzLin_one, LinearMap.toMatrix'_id]

theorem lorentzMat_apply (A : Matrix (Fin 2) (Fin 2) ℂ) (i j : Fin 4) :
    lorentzMat A i j = lorentzMap A (Pi.single j 1) i := by
  rw [lorentzMat, LinearMap.toMatrix'_apply]; rfl

/-! ## 4. The image lies in the orthogonal group of the form -/

theorem bil_preserved (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1)
    (v w : Fin 4 → ℝ) :
    bil (lorentzMap A v) (lorentzMap A w) = bil v w := by
  have hsum : lorentzMap A (v + w) = lorentzMap A v + lorentzMap A w :=
    lorentzMap_add A v w
  have h1 := minkowskiForm_lorentzMap A hA (v + w)
  rw [hsum, polarization, polarization] at h1
  rw [minkowskiForm_lorentzMap A hA v, minkowskiForm_lorentzMap A hA w] at h1
  linarith

theorem bil_single (i j : Fin 4) :
    bil (Pi.single i (1 : ℝ)) (Pi.single j 1) = gram i j := by
  fin_cases i <;> fin_cases j <;>
    simp [bil, gram, mw]

/-- **The image lies in O(1,3)**, as a matrix identity. -/
theorem lorentzMat_gram (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    (lorentzMat A)ᵀ * gram * lorentzMat A = gram := by
  ext i j
  have hb := bil_preserved A hA (Pi.single i 1) (Pi.single j 1)
  rw [bil_single] at hb
  have hcol : ∀ (k l : Fin 4),
      lorentzMap A (Pi.single l (1 : ℝ)) k = lorentzMat A k l := fun k l =>
    (lorentzMat_apply A k l).symm
  rw [bil] at hb
  rw [hcol, hcol, hcol, hcol, hcol, hcol, hcol, hcol] at hb
  rw [Matrix.mul_assoc, Matrix.mul_apply, Fin.sum_univ_four]
  simp only [Matrix.transpose_apply, gram, Matrix.diagonal_mul]
  rw [show mw 0 = 1 from rfl, show mw 1 = -1 from rfl, show mw 2 = -1 from rfl,
    show mw 3 = -1 from rfl]
  rw [gram] at hb
  linarith [hb]

/-- Any isometry of the Minkowski form has determinant ±1. -/
theorem det_lorentzMat_sq (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    (lorentzMat A).det ^ 2 = 1 := by
  have h := congrArg Matrix.det (lorentzMat_gram A hA)
  rw [Matrix.det_mul, Matrix.det_mul, Matrix.det_transpose, det_gram] at h
  nlinarith [h]


/-! ## 5. Properness: det Λ(A) = +1, by square roots inside SL₂(ℂ)

    The usual proof that the image is proper is topological: det Λ is
    continuous, valued in {±1}, and SL₂(ℂ) is connected. That argument is not
    available here, and it is not needed. Every element of SL₂(ℂ) is a
    product of squares, by an explicit formula, and det Λ of a square is a
    square of ±1. -/

/-- Cayley–Hamilton in 2×2, proved entrywise. -/
theorem cayley_two (A : Matrix (Fin 2) (Fin 2) ℂ) :
    A * A = (A 0 0 + A 1 1) • A - A.det • 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_two, Matrix.det_fin_two] <;>
    ring

/-- **An explicit square root inside SL₂(ℂ)**: if tr A ≠ −2 then
    N = (A + 1)/s with s² = tr A + 2 satisfies det N = 1 and N² = A.
    The verification is Cayley–Hamilton: (A + 1)² = (tr A + 2)·A when
    det A = 1. -/
theorem exists_sqrt_of_trace_ne (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1)
    (htr : A 0 0 + A 1 1 + 2 ≠ 0) :
    ∃ N : Matrix (Fin 2) (Fin 2) ℂ, N.det = 1 ∧ N * N = A := by
  obtain ⟨s, hs⟩ :=
    IsAlgClosed.exists_pow_nat_eq (A 0 0 + A 1 1 + 2) (n := 2) (by norm_num)
  have hs0 : s ≠ 0 := by
    intro h
    apply htr
    rw [← hs, h]
    ring
  have hd : A 0 0 * A 1 1 - A 0 1 * A 1 0 = 1 := by
    rw [← Matrix.det_fin_two]; exact hA
  have hkey : (A + 1) * (A + 1) = (A 0 0 + A 1 1 + 2) • A := by
    have hc := cayley_two A
    rw [hA] at hc
    have hexp : (A + 1) * (A + 1) = A * A + A + A + 1 := by noncomm_ring
    rw [hexp, hc, one_smul]
    module
  refine ⟨s⁻¹ • (A + 1), ?_, ?_⟩
  · have hdet1 : (A + 1).det = A 0 0 + A 1 1 + 2 := by
      rw [Matrix.det_fin_two]
      have h00 : (A + 1) 0 0 = A 0 0 + 1 := by
        rw [Matrix.add_apply, Matrix.one_apply_eq]
      have h11 : (A + 1) 1 1 = A 1 1 + 1 := by
        rw [Matrix.add_apply, Matrix.one_apply_eq]
      have h01 : (A + 1) 0 1 = A 0 1 := by
        rw [Matrix.add_apply, Matrix.one_apply_ne (by decide), add_zero]
      have h10 : (A + 1) 1 0 = A 1 0 := by
        rw [Matrix.add_apply, Matrix.one_apply_ne (by decide), add_zero]
      rw [h00, h11, h01, h10]
      linear_combination hd
    rw [Matrix.det_smul, Fintype.card_fin, hdet1, ← hs]
    field_simp
  · rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul, hkey, smul_smul, ← hs]
    rw [show s⁻¹ * s⁻¹ * (s ^ 2) = 1 by field_simp, one_smul]

/-- J = [[0, −1], [1, 0]]: a square root of −1 inside SL₂(ℂ). It is what
    makes the exceptional trace = −2 case go through. -/
def Jmat : Matrix (Fin 2) (Fin 2) ℂ := !![0, -1; 1, 0]

theorem det_Jmat : Jmat.det = 1 := by
  rw [Matrix.det_fin_two]; simp [Jmat]

theorem Jmat_mul_Jmat : Jmat * Jmat = -1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Jmat, Matrix.mul_apply, Fin.sum_univ_two]

/-- **The image is PROPER**: det Λ(A) = +1 for every A ∈ SL₂(ℂ). -/
theorem det_lorentzMat (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    (lorentzMat A).det = 1 := by
  by_cases htr : A 0 0 + A 1 1 + 2 = 0
  · have hA' : (-A).det = 1 := by
      rw [Matrix.det_neg, Fintype.card_fin, hA]; norm_num
    have htr' : (-A) 0 0 + (-A) 1 1 + 2 ≠ 0 := by
      simp only [Matrix.neg_apply]
      intro h
      have h4 : (4 : ℂ) = 0 := by linear_combination htr + h
      norm_num at h4
    obtain ⟨N, hNdet, hN⟩ := exists_sqrt_of_trace_ne (-A) hA' htr'
    have hfac : A = (Jmat * Jmat) * (N * N) := by
      rw [Jmat_mul_Jmat, hN]
      ext i j
      simp
    have h1 := det_lorentzMat_sq Jmat det_Jmat
    have h2 := det_lorentzMat_sq N hNdet
    rw [hfac]
    simp only [lorentzMat_mul, Matrix.det_mul]
    nlinarith [h1, h2]
  · obtain ⟨N, hNdet, hN⟩ := exists_sqrt_of_trace_ne A hA htr
    rw [← hN, lorentzMat_mul, Matrix.det_mul, ← sq]
    exact det_lorentzMat_sq N hNdet

/-! ## 6. Orthochronicity: Λ(A)⁰₀ ≥ 1

    The time-time entry of the Lorentz matrix is half the squared
    Frobenius norm of A, and det A = 1 forces that to be at least 2. -/

theorem lorentzMat_zero_zero (A : Matrix (Fin 2) (Fin 2) ℂ) :
    lorentzMat A 0 0 =
      (Complex.normSq (A 0 0) + Complex.normSq (A 0 1) + Complex.normSq (A 1 0)
        + Complex.normSq (A 1 1)) / 2 := by
  have e0 : (Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 0 = 1 := by simp
  have e1 : (Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 1 = 0 := by simp
  have e2 : (Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 2 = 0 := by simp
  have e3 : (Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 3 = 0 := by simp
  have hone : pauliHerm (1 : ℝ) 0 0 0 = 1 := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [pauliHerm]
  rw [lorentzMat_apply]
  change pauliCoord (A * pauliHerm ((Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 0)
      ((Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 1) ((Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 2)
      ((Pi.single (0 : Fin 4) 1 : Fin 4 → ℝ) 3) * Aᴴ) 0 = _
  rw [e0, e1, e2, e3]
  rw [hone, Matrix.mul_one]
  simp only [pauliCoord, Matrix.cons_val_zero, Matrix.mul_apply, Fin.sum_univ_two,
    Matrix.conjTranspose_apply, Complex.add_re, Complex.mul_re, Complex.conj_re,
    Complex.conj_im, Complex.normSq_apply, RCLike.star_def]
  ring

/-- **The image is ORTHOCHRONOUS**, with the sharp constant: Λ(A)⁰₀ ≥ 1, and
    equality holds at A = 1. The proof is |ad − bc| = 1 plus AM–GM. -/
theorem one_le_lorentzMat_zero_zero (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    1 ≤ lorentzMat A 0 0 := by
  have hd : A 0 0 * A 1 1 - A 0 1 * A 1 0 = 1 := by
    rw [← Matrix.det_fin_two]; exact hA
  have h1 : ‖A 0 0 * A 1 1 - A 0 1 * A 1 0‖ = 1 := by rw [hd]; simp
  have h2 : (1 : ℝ) ≤ ‖A 0 0‖ * ‖A 1 1‖ + ‖A 0 1‖ * ‖A 1 0‖ :=
    calc (1 : ℝ) = ‖A 0 0 * A 1 1 - A 0 1 * A 1 0‖ := h1.symm
      _ ≤ ‖A 0 0 * A 1 1‖ + ‖A 0 1 * A 1 0‖ := norm_sub_le _ _
      _ = ‖A 0 0‖ * ‖A 1 1‖ + ‖A 0 1‖ * ‖A 1 0‖ := by rw [norm_mul, norm_mul]
  rw [lorentzMat_zero_zero, Complex.normSq_eq_norm_sq, Complex.normSq_eq_norm_sq,
    Complex.normSq_eq_norm_sq, Complex.normSq_eq_norm_sq]
  nlinarith [two_mul_le_add_sq ‖A 0 0‖ ‖A 1 1‖, two_mul_le_add_sq ‖A 0 1‖ ‖A 1 0‖, h2]

/-! ## 7. O(1,3) and SO⁺(1,3) as bundled subgroups of GL₄(ℝ)

    Mathlib has `Matrix.orthogonalGroup` for the standard (definite) form and
    `unitaryGroup`, but no group of isometries of an indefinite form. These
    are built here from the Gram identity. -/

/-- The Lorentz condition on a 4×4 real matrix: it preserves the Minkowski
    Gram matrix. -/
def IsLorentzMat (M : Matrix (Fin 4) (Fin 4) ℝ) : Prop := Mᵀ * gram * M = gram

theorem IsLorentzMat.mul {M N : Matrix (Fin 4) (Fin 4) ℝ}
    (hM : IsLorentzMat M) (hN : IsLorentzMat N) : IsLorentzMat (M * N) :=
  calc (M * N)ᵀ * gram * (M * N) = Nᵀ * (Mᵀ * gram * M) * N := by
        rw [Matrix.transpose_mul]; noncomm_ring
    _ = gram := by rw [hM]; exact hN

theorem IsLorentzMat.one : IsLorentzMat (1 : Matrix (Fin 4) (Fin 4) ℝ) := by
  rw [IsLorentzMat, Matrix.transpose_one, Matrix.one_mul, Matrix.mul_one]

/-- If M is Lorentz and B is a right inverse of M, then B is Lorentz. -/
theorem IsLorentzMat.of_mul_eq_one {M B : Matrix (Fin 4) (Fin 4) ℝ}
    (hM : IsLorentzMat M) (h : M * B = 1) : IsLorentzMat B :=
  calc Bᵀ * gram * B = Bᵀ * (Mᵀ * gram * M) * B := by rw [hM]
    _ = (M * B)ᵀ * gram * (M * B) := by rw [Matrix.transpose_mul]; noncomm_ring
    _ = gram := by rw [h, Matrix.transpose_one, Matrix.one_mul, Matrix.mul_one]

/-- **The Lorentz group O(1,3)**: the isometries of the Minkowski form, as a
    genuine subgroup of GL₄(ℝ). -/
def O13 : Subgroup (Matrix.GeneralLinearGroup (Fin 4) ℝ) where
  carrier := {M | IsLorentzMat (M : Matrix (Fin 4) (Fin 4) ℝ)}
  mul_mem' := by
    intro M N hM hN
    change IsLorentzMat _
    rw [Matrix.GeneralLinearGroup.coe_mul]
    exact hM.mul hN
  one_mem' := by
    change IsLorentzMat _
    rw [Units.val_one]
    exact IsLorentzMat.one
  inv_mem' := by
    intro M hM
    exact IsLorentzMat.of_mul_eq_one hM (Units.mul_inv M)

theorem mem_O13 {M : Matrix.GeneralLinearGroup (Fin 4) ℝ} :
    M ∈ O13 ↔ IsLorentzMat (M : Matrix (Fin 4) (Fin 4) ℝ) := Iff.rfl

/-- The inverse of a Lorentz matrix is G Mᵀ G — the familiar index-lowering
    formula, here as a theorem. -/
theorem inv_eq_gram_conj {M B : Matrix (Fin 4) (Fin 4) ℝ} (hM : IsLorentzMat M)
    (h : M * B = 1) : B = gram * Mᵀ * gram := by
  have hleft : (gram * Mᵀ * gram) * M = 1 :=
    calc (gram * Mᵀ * gram) * M = gram * (Mᵀ * gram * M) := by noncomm_ring
      _ = gram * gram := by rw [hM]
      _ = 1 := gram_mul_gram
  calc B = ((gram * Mᵀ * gram) * M) * B := by rw [hleft, Matrix.one_mul]
    _ = (gram * Mᵀ * gram) * (M * B) := by noncomm_ring
    _ = gram * Mᵀ * gram := by rw [h, Matrix.mul_one]

/-- The column form of the Gram identity implies the row form. -/
theorem gram_row {M : Matrix (Fin 4) (Fin 4) ℝ} (h : IsLorentzMat M) :
    M * gram * Mᵀ = gram := by
  have hleft : (gram * Mᵀ * gram) * M = 1 :=
    calc (gram * Mᵀ * gram) * M = gram * (Mᵀ * gram * M) := by noncomm_ring
      _ = gram * gram := by rw [h]
      _ = 1 := gram_mul_gram
  have hright : M * (gram * Mᵀ * gram) = 1 := mul_eq_one_comm.mp hleft
  calc M * gram * Mᵀ = M * gram * Mᵀ * (gram * gram) := by
        rw [gram_mul_gram, Matrix.mul_one]
    _ = (M * (gram * Mᵀ * gram)) * gram := by noncomm_ring
    _ = gram := by rw [hright, Matrix.one_mul]

/-- The first row of a Lorentz matrix is a unit timelike vector. -/
theorem row_zero_norm {M : Matrix (Fin 4) (Fin 4) ℝ} (h : IsLorentzMat M) :
    M 0 0 ^ 2 - M 0 1 ^ 2 - M 0 2 ^ 2 - M 0 3 ^ 2 = 1 := by
  have hr := congrFun (congrFun (gram_row h) 0) 0
  rw [Matrix.mul_apply, Fin.sum_univ_four] at hr
  simp only [gram, Matrix.mul_diagonal, Matrix.transpose_apply,
    Matrix.diagonal_apply_eq] at hr
  rw [show mw 0 = 1 from rfl, show mw 1 = -1 from rfl, show mw 2 = -1 from rfl,
    show mw 3 = -1 from rfl] at hr
  nlinarith [hr]

/-- The first column of a Lorentz matrix is a unit timelike vector. -/
theorem col_zero_norm {M : Matrix (Fin 4) (Fin 4) ℝ} (h : IsLorentzMat M) :
    M 0 0 ^ 2 - M 1 0 ^ 2 - M 2 0 ^ 2 - M 3 0 ^ 2 = 1 := by
  have hr := congrFun (congrFun h 0) 0
  rw [Matrix.mul_apply, Fin.sum_univ_four] at hr
  simp only [gram, Matrix.mul_diagonal, Matrix.transpose_apply,
    Matrix.diagonal_apply_eq] at hr
  rw [show mw 0 = 1 from rfl, show mw 1 = -1 from rfl, show mw 2 = -1 from rfl,
    show mw 3 = -1 from rfl] at hr
  nlinarith [hr]

/-- **Orthochronicity is closed under multiplication.** This is the one
    non-formal step in making SO⁺(1,3) a group: it is a Cauchy–Schwarz
    argument on the space directions, and it is why the orthochronous
    transformations form a subgroup while, say, {Λ⁰₀ ≥ 2} does not. -/
theorem orthochronous_mul {M N : Matrix (Fin 4) (Fin 4) ℝ}
    (hM : IsLorentzMat M) (hN : IsLorentzMat N)
    (hM0 : 0 < M 0 0) (hN0 : 0 < N 0 0) : 0 < (M * N) 0 0 := by
  have hx := row_zero_norm hM
  have hy := col_zero_norm hN
  have ha1 : 1 ≤ M 0 0 := by
    nlinarith [sq_nonneg (M 0 1), sq_nonneg (M 0 2), sq_nonneg (M 0 3)]
  have hb1 : 1 ≤ N 0 0 := by
    nlinarith [sq_nonneg (N 1 0), sq_nonneg (N 2 0), sq_nonneg (N 3 0)]
  have hcs : (M 0 1 * N 1 0 + M 0 2 * N 2 0 + M 0 3 * N 3 0) ^ 2
      ≤ (M 0 0 ^ 2 - 1) * (N 0 0 ^ 2 - 1) := by
    nlinarith [sq_nonneg (M 0 1 * N 2 0 - M 0 2 * N 1 0),
      sq_nonneg (M 0 1 * N 3 0 - M 0 3 * N 1 0),
      sq_nonneg (M 0 2 * N 3 0 - M 0 3 * N 2 0), hx, hy]
  rw [Matrix.mul_apply, Fin.sum_univ_four]
  by_contra hcon
  rw [not_lt] at hcon
  have hprod : 0 < M 0 0 * N 0 0 := mul_pos hM0 hN0
  have hgap : 1 ≤ (M 0 0 * N 0 0) ^ 2
      - (M 0 1 * N 1 0 + M 0 2 * N 2 0 + M 0 3 * N 3 0) ^ 2 := by
    nlinarith [hcs, ha1, hb1]
  nlinarith [hgap, hcon, hprod]

/-- **The proper orthochronous Lorentz group SO⁺(1,3)**, as a subgroup of
    GL₄(ℝ): isometries of the Minkowski form with det = 1 that preserve the
    direction of time. -/
def SOplus13 : Subgroup (Matrix.GeneralLinearGroup (Fin 4) ℝ) where
  carrier := {M | IsLorentzMat (M : Matrix (Fin 4) (Fin 4) ℝ)
      ∧ (M : Matrix (Fin 4) (Fin 4) ℝ).det = 1 ∧ 0 < (M : Matrix (Fin 4) (Fin 4) ℝ) 0 0}
  mul_mem' := by
    rintro M N ⟨hM, hMd, hM0⟩ ⟨hN, hNd, hN0⟩
    refine ⟨?_, ?_, ?_⟩
    · change IsLorentzMat _
      rw [Matrix.GeneralLinearGroup.coe_mul]; exact hM.mul hN
    · rw [Matrix.GeneralLinearGroup.coe_mul, Matrix.det_mul, hMd, hNd, mul_one]
    · rw [Matrix.GeneralLinearGroup.coe_mul]
      exact orthochronous_mul hM hN hM0 hN0
  one_mem' := by
    refine ⟨?_, ?_, ?_⟩
    · change IsLorentzMat _
      rw [Units.val_one]; exact IsLorentzMat.one
    · rw [Units.val_one, Matrix.det_one]
    · rw [Units.val_one, Matrix.one_apply_eq]; norm_num
  inv_mem' := by
    rintro M ⟨hM, hMd, hM0⟩
    have hinv : ((M⁻¹ : Matrix.GeneralLinearGroup (Fin 4) ℝ) : Matrix (Fin 4) (Fin 4) ℝ)
        = gram * (M : Matrix (Fin 4) (Fin 4) ℝ)ᵀ * gram :=
      inv_eq_gram_conj hM (Units.mul_inv M)
    refine ⟨IsLorentzMat.of_mul_eq_one hM (Units.mul_inv M), ?_, ?_⟩
    · rw [hinv, Matrix.det_mul, Matrix.det_mul, Matrix.det_transpose, det_gram, hMd]
      norm_num
    · rw [hinv, Matrix.mul_assoc]
      simp only [gram, Matrix.diagonal_mul, Matrix.mul_diagonal, Matrix.transpose_apply]
      rw [show mw 0 = 1 from rfl]
      simpa using hM0

/-! ## 8. The homomorphism SL₂(ℂ) → SO⁺(1,3) -/

/-- Λ(A) as an element of GL₄(ℝ). -/
def lorentzUnit (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    Matrix.GeneralLinearGroup (Fin 4) ℝ where
  val := lorentzMat A
  inv := lorentzMat A⁻¹
  val_inv := by
    rw [← lorentzMat_mul, Matrix.mul_nonsing_inv A (by rw [hA]; exact isUnit_one),
      lorentzMat_one]
  inv_val := by
    rw [← lorentzMat_mul, Matrix.nonsing_inv_mul A (by rw [hA]; exact isUnit_one),
      lorentzMat_one]

@[simp] theorem lorentzUnit_val (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    (lorentzUnit A hA : Matrix (Fin 4) (Fin 4) ℝ) = lorentzMat A := rfl

/-- **Step (i): the image is inside the orthogonal group of the form**, as a
    bundled subgroup element. -/
theorem lorentzUnit_mem_O13 (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    lorentzUnit A hA ∈ O13 := lorentzMat_gram A hA

/-- **Step (ii): the image is inside SO⁺(1,3)** — proper and orthochronous. -/
theorem lorentzUnit_mem_SOplus13 (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1) :
    lorentzUnit A hA ∈ SOplus13 :=
  ⟨lorentzMat_gram A hA, det_lorentzMat A hA,
    lt_of_lt_of_le zero_lt_one (one_le_lorentzMat_zero_zero A hA)⟩

/-- **The whole content of this file in one statement**: the SL₂(ℂ) action on
    Minkowski space is a multiplicative map into the proper orthochronous
    Lorentz group, and its kernel is exactly {±1}. What is NOT here is
    surjectivity. -/
theorem lorentz_action_summary :
    (∀ A B : Matrix (Fin 2) (Fin 2) ℂ, lorentzMat (A * B) = lorentzMat A * lorentzMat B)
      ∧ lorentzMat (1 : Matrix (Fin 2) (Fin 2) ℂ) = 1
      ∧ (∀ (A : Matrix (Fin 2) (Fin 2) ℂ) (hA : A.det = 1), lorentzUnit A hA ∈ SOplus13)
      ∧ (∀ A : Matrix (Fin 2) (Fin 2) ℂ, A.det = 1 →
          (∀ H : Matrix (Fin 2) (Fin 2) ℂ, Hᴴ = H → A * H * Aᴴ = H) → A = 1 ∨ A = -1) :=
  ⟨lorentzMat_mul, lorentzMat_one, lorentzUnit_mem_SOplus13,
    fun A hA hfix => kernel_of_conj_action A hA hfix⟩

end LorentzGroup
