import LovelockOrthogonality

/-!
# The pair projector, and the `ip`-orthogonal machinery it comes with

`WALLS` §W5.0 §5d leaves the route to `KillsWeyl` open at two places, and both are the same thing:
`LovelockReduction`'s equivariance hypothesis is assumed only at algebraic curvature tensors, while
`LovelockAdjoint`'s adjoint is built from the standard basis, whose members are not algebraic
curvature tensors. **The way to close both is an explicit projection onto the algebraic curvature
tensors**, and this file is the first of the two steps it needs.

## What is proved

* `ip_eq_prod` — the full contraction as a single sum over the quadruple index, which is the form
  every reindexing below wants;
* `sum_reindex` and `ip_perm_0` … `ip_perm_7` — **permuting the four slots does not change the full
  contraction**, for each of the eight slot permutations generated by the two pair swaps and the
  pair exchange. This is `Fintype.sum_equiv` eight times and nothing more;
* **`pairProj`** — one eighth of the alternating sum over those eight permutations, and
  `pairProj_antisymm_left`, `pairProj_antisymm_right`, `pairProj_pair_symm`: **the result satisfies
  three of the four `IsAlgCurv` clauses**, for *every* input array, with no hypothesis at all;
* **`pairProj_eq_self`** — and it is the identity on arrays that already have those three
  symmetries. So it is a projection in the ordinary sense;
* **`ip_pairProj_left`** — `⟨pairProj A, B⟩ = ⟨A, B⟩` whenever `B` has the three symmetries. **This
  is the property the route needs**: testing against a symmetric object cannot tell `A` from its
  symmetrisation.

## What this does NOT do, and it is exactly one clause

**`pairProj A` is not an algebraic curvature tensor.** `IsAlgCurv` has four clauses and this
supplies three; **the first Bianchi identity is not imposed**, and the arrays satisfying the three
symmetries form a strictly larger space than `Curv` for `n ≥ 3`. Removing the Bianchi component is
a second projection, and it is not here.

**So §5d's gaps (i) and (ii) are NOT closed by this file**, and nothing in it should be read as
closing them. What it establishes is that the *first* half of the construction they need is
elementary: eight reindexings and a `ring`. **The watchlist item does not move.**

**And `ip` invariance under slot permutations is a fact about the form, not about curvature.**
`ip_perm_0` … `ip_perm_7` carry no hypothesis on either argument. They are stated separately from
`pairProj` because they are reusable and because the symmetrisation is the only place this file
uses them.

Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

namespace LovelockPairProjection

open AlgebraicCurvature LovelockProjections LovelockOrthogonality Finset

variable {n : ℕ}

/-! ## 1. The contraction as one sum, and the eight reindexings -/

theorem ip_eq_prod (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ip A B = ∑ p : Fin n × Fin n × Fin n × Fin n,
      A p.1 p.2.1 p.2.2.1 p.2.2.2 * B p.1 p.2.1 p.2.2.1 p.2.2.2 := by
  simp only [ip, Fintype.sum_prod_type]

theorem ip_sw12 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ip (fun a b c d => A b a c d) B = ip A (fun a b c d => B b a c d) := by
  rw [ip_eq_prod, ip_eq_prod]
  exact Fintype.sum_equiv
    ⟨fun p => (p.2.1, p.1, p.2.2.1, p.2.2.2), fun p => (p.2.1, p.1, p.2.2.1, p.2.2.2),
     fun _ => rfl, fun _ => rfl⟩ _ _ fun _ => rfl

theorem ip_sw34 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ip (fun a b c d => A a b d c) B = ip A (fun a b c d => B a b d c) := by
  rw [ip_eq_prod, ip_eq_prod]
  exact Fintype.sum_equiv
    ⟨fun p => (p.1, p.2.1, p.2.2.2, p.2.2.1), fun p => (p.1, p.2.1, p.2.2.2, p.2.2.1),
     fun _ => rfl, fun _ => rfl⟩ _ _ fun _ => rfl

theorem ip_swp (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ip (fun a b c d => A c d a b) B = ip A (fun a b c d => B c d a b) := by
  rw [ip_eq_prod, ip_eq_prod]
  exact Fintype.sum_equiv
    ⟨fun p => (p.2.2.1, p.2.2.2, p.1, p.2.1), fun p => (p.2.2.1, p.2.2.2, p.1, p.2.1),
     fun _ => rfl, fun _ => rfl⟩ _ _ fun _ => rfl

/-- The projection onto arrays antisymmetric in each pair and symmetric under pair exchange. -/
noncomputable def pairProj (A : Fin n → Fin n → Fin n → Fin n → ℝ) (a b c d : Fin n) : ℝ :=
  (1/8 : ℝ) * (A a b c d - A b a c d - A a b d c + A b a d c
    + A c d a b - A d c a b - A c d b a + A d c b a)

theorem pairProj_antisymm_left (A : Fin n → Fin n → Fin n → Fin n → ℝ) (a b c d : Fin n) :
    pairProj A a b c d = -pairProj A b a c d := by
  simp only [pairProj]; ring

theorem pairProj_antisymm_right (A : Fin n → Fin n → Fin n → Fin n → ℝ) (a b c d : Fin n) :
    pairProj A a b c d = -pairProj A a b d c := by
  simp only [pairProj]; ring

theorem pairProj_pair_symm (A : Fin n → Fin n → Fin n → Fin n → ℝ) (a b c d : Fin n) :
    pairProj A a b c d = pairProj A c d a b := by
  simp only [pairProj]; ring

theorem pairProj_eq_self {A : Fin n → Fin n → Fin n → Fin n → ℝ}
    (h1 : ∀ a b c d, A a b c d = -A b a c d) (h2 : ∀ a b c d, A a b c d = -A a b d c)
    (h3 : ∀ a b c d, A a b c d = A c d a b) (a b c d : Fin n) :
    pairProj A a b c d = A a b c d := by
  have e1 : A b a c d = -A a b c d := by have := h1 a b c d; linarith
  have e2 : A a b d c = -A a b c d := by have := h2 a b c d; linarith
  have e3 : A b a d c = A a b c d := by have := h1 a b d c; linarith
  have e4 : A c d a b = A a b c d := (h3 a b c d).symm
  have e5 : A d c a b = -A a b c d := by have := h1 c d a b; linarith
  have e6 : A c d b a = -A a b c d := by have := h2 c d a b; linarith
  have e7 : A d c b a = A a b c d := by have := h1 c d b a; linarith
  simp only [pairProj, e1, e2, e3, e4, e5, e6, e7]
  ring

theorem sum_reindex (e : (Fin n × Fin n × Fin n × Fin n) ≃ (Fin n × Fin n × Fin n × Fin n))
    (F : Fin n × Fin n × Fin n × Fin n → ℝ) : ∑ p, F (e p) = ∑ p, F p :=
  Fintype.sum_equiv e _ _ fun _ => rfl

theorem ip_perm_0 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.1 p.2.1 p.2.2.1 p.2.2.2 * B p.1 p.2.1 p.2.2.1 p.2.2.2 = ip A B :=
  (ip_eq_prod A B).symm

theorem ip_perm_1 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.1 p.1 p.2.2.1 p.2.2.2 * B p.2.1 p.1 p.2.2.1 p.2.2.2 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.1, p.1, p.2.2.1, p.2.2.2), fun p => (p.2.1, p.1, p.2.2.1, p.2.2.2),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_2 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.1 p.2.1 p.2.2.2 p.2.2.1 * B p.1 p.2.1 p.2.2.2 p.2.2.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.1, p.2.1, p.2.2.2, p.2.2.1), fun p => (p.1, p.2.1, p.2.2.2, p.2.2.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_3 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.1 p.1 p.2.2.2 p.2.2.1 * B p.2.1 p.1 p.2.2.2 p.2.2.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.1, p.1, p.2.2.2, p.2.2.1), fun p => (p.2.1, p.1, p.2.2.2, p.2.2.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_4 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.2.1 p.2.2.2 p.1 p.2.1 * B p.2.2.1 p.2.2.2 p.1 p.2.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.2.1, p.2.2.2, p.1, p.2.1), fun p => (p.2.2.1, p.2.2.2, p.1, p.2.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_5 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.2.2 p.2.2.1 p.1 p.2.1 * B p.2.2.2 p.2.2.1 p.1 p.2.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.2.2, p.2.2.1, p.1, p.2.1), fun p => (p.2.2.1, p.2.2.2, p.2.1, p.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_6 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.2.1 p.2.2.2 p.2.1 p.1 * B p.2.2.1 p.2.2.2 p.2.1 p.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.2.1, p.2.2.2, p.2.1, p.1), fun p => (p.2.2.2, p.2.2.1, p.1, p.2.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_perm_7 (A B : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ∑ p : Fin n × Fin n × Fin n × Fin n,
        A p.2.2.2 p.2.2.1 p.2.1 p.1 * B p.2.2.2 p.2.2.1 p.2.1 p.1 = ip A B := by
  rw [ip_eq_prod]
  exact sum_reindex
    ⟨fun p => (p.2.2.2, p.2.2.1, p.2.1, p.1), fun p => (p.2.2.2, p.2.2.1, p.2.1, p.1),
     fun _ => rfl, fun _ => rfl⟩
    (fun q => A q.1 q.2.1 q.2.2.1 q.2.2.2 * B q.1 q.2.1 q.2.2.1 q.2.2.2)

theorem ip_pairProj_left {B : Fin n → Fin n → Fin n → Fin n → ℝ}
    (h1 : ∀ a b c d, B a b c d = -B b a c d) (h2 : ∀ a b c d, B a b c d = -B a b d c)
    (h3 : ∀ a b c d, B a b c d = B c d a b) (A : Fin n → Fin n → Fin n → Fin n → ℝ) :
    ip (pairProj A) B = ip A B := by
  have hsummand : ∀ a b c d : Fin n,
      pairProj A a b c d * B a b c d
        = (1/8 : ℝ) * (A a b c d * B a b c d)
          + (1/8 : ℝ) * (A b a c d * B b a c d)
          + (1/8 : ℝ) * (A a b d c * B a b d c)
          + (1/8 : ℝ) * (A b a d c * B b a d c)
          + (1/8 : ℝ) * (A c d a b * B c d a b)
          + (1/8 : ℝ) * (A d c a b * B d c a b)
          + (1/8 : ℝ) * (A c d b a * B c d b a)
          + (1/8 : ℝ) * (A d c b a * B d c b a) := by
    intro a b c d
    simp only [pairProj]
    have f1 : B b a c d = -B a b c d := by have := h1 a b c d; linarith
    have f2 : B a b d c = -B a b c d := by have := h2 a b c d; linarith
    have f3 : B b a d c = B a b c d := by have := h1 a b d c; linarith
    have f4 : B c d a b = B a b c d := (h3 a b c d).symm
    have f5 : B d c a b = -B a b c d := by have := h1 c d a b; linarith
    have f6 : B c d b a = -B a b c d := by have := h2 c d a b; linarith
    have f7 : B d c b a = B a b c d := by have := h1 c d b a; linarith
    rw [f1, f2, f3, f4, f5, f6, f7]
    ring
  rw [ip_eq_prod (pairProj A) B, Finset.sum_congr rfl fun p _ => hsummand p.1 p.2.1 p.2.2.1 p.2.2.2]
  simp only [Finset.sum_add_distrib, ← Finset.mul_sum, ip_perm_0, ip_perm_1, ip_perm_2,
    ip_perm_3, ip_perm_4, ip_perm_5, ip_perm_6, ip_perm_7]
  ring

end LovelockPairProjection
