/-
  OS2MeasureLevel: Reflection Positivity as a Statement About a MEASURE
  =====================================================================

  The last stair of the OS2 staircase (UNLOCK_WATCHLIST, item "measure-level
  OS2 packaging"). `OS2ProductField` proved reflection positivity of the
  OU-product covariance in every dimension — at the level of matrices and
  quadratic forms. This file builds the FIELD: an honest probability measure
  on ℝ^sites, and proves OS2 as a statement about integrals against it.

  The Gaussian vector itself comes from Mathlib: `multivariateGaussian`
  (Probability.Distributions.Gaussian.Multivariate) with its covariance API
  (`covariance_eval_multivariateGaussian`). The watchlist's step M1 mapped a
  hand construction as pushforward of iid Gaussians under a Gram factor and
  an ALTERNATIVE — "probe whether Mathlib already ships a multivariate
  Gaussian; if yes, use it and record the name". The alternative fired.

  WHAT THIS FILE PROVES (exactly this, nothing more):

  1. `ouCov_posSemidef_index` — the 1-d exponential covariance is PSD on
     sites indexed by ANY finite type (transport of `ouCov_posSemidef_all`
     along `Fintype.equivFin` via `PosSemidef.submatrix`).
  2. `prodCov` / `prodCov_posSemidef` — the UNREFLECTED OU-product
     covariance matrix on an arbitrary finite site family is PSD (iterated
     Schur). NOTE: unlike the reflected covariance-level results, the TIME
     rate here needs 0 ≤ Δ 0 — unreflected, the time factor is itself an
     OU covariance, not a rank-one Gram matrix.
  3. `fieldMeasure` — THE FIELD: the centred `multivariateGaussian` with
     covariance `prodCov`, a genuine probability measure on
     `EuclideanSpace ℝ ι`; `memLp_eval`, `integral_eval` (each coordinate
     field is L² with mean zero), and **`twoPoint`**:
     ∫ ω(a)·ω(b) dμ = C(zₐ, z_b) — the two-point function IS the
     covariance kernel.
  4. **`integral_pairing`** — for the doubled site family (N positive-time
     sites ⊕ their θ-reflections) and the linear observables
     F(ω) = Σᵢ cᵢ·ω(site i), F^θ(ω) = Σⱼ cⱼ·ω(reflected site j):

        ∫ F·F^θ dμ  =  Σᵢⱼ cᵢcⱼ · Πₖ e^{−Δₖ|zᵢₖ − (θz)ⱼₖ|}

     — the measure pairing equals the reflected covariance form, EXACTLY.
  5. **`os2_measure_level`** — MEASURE-LEVEL REFLECTION POSITIVITY:
     0 ≤ ∫ F·F^θ dμ for every dimension m + 1, every finite positive-time
     site family, every test vector. The right side of item 4 is
     `OS2ProductField.os2_reflection`.
  6. `os2_measure_level_attained` — non-vacuity: at a single site the
     integral EQUALS e^{−2Δ₀x}·c² > 0; the pairing is a genuine positive
     number, not an empty statement.

  WHAT THIS IS AND IS NOT (the honesty box):

  * LINEAR observables at FINITELY many sites. The full OS reflection-
    positivity axiom quantifies over the *-algebra generated by the
    exponentials e^{iφ(f)} of positive-time fields; the linear case proven
    here is its two-point core. The exponential extension has a named
    stair: Mathlib's `charFun_multivariateGaussian` computes
    E[e^{i⟪t,X⟫}] = e^{−tᵀSt/2}, so the Gaussian-specific identity needed
    is in place — recorded on UNLOCK_WATCHLIST, not claimed here.
  * A field on FINITE site families, not a measure on a function space:
    no projective limit, no continuum field, no Osterwalder–Schrader
    reconstruction. Mathlib's `measurePreserving_restrict₂` gives marginal
    consistency of these finite-dimensional distributions, which is the
    Kolmogorov-extension INPUT, but the extension itself is not taken here.
  * The OU-PRODUCT covariance, NOT the lattice-Laplacian Green function —
    the same scope boundary as every file on this staircase, stated loudly
    since the staircase was mapped.
  * The `_proof_004_logos` sorry is NOT touched. Its watchlist item says:
    revisit after this lands. It should be revisited with THIS scope
    boundary in view.

  Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new axioms.
-/

import OS2ProductField
import SchurProduct
import Mathlib.Probability.Distributions.Gaussian.Multivariate

open MeasureTheory ProbabilityTheory Matrix Real Finset
open scoped RealInnerProductSpace

set_option backward.isDefEq.respectTransparency false

noncomputable section

namespace OS2MeasureLevel

open OS2ProductField

variable {m : ℕ}

/-! ## 1. The unreflected OU-product covariance on arbitrary finite families -/

/-- The OU-product covariance kernel as a matrix on an arbitrary finite
    family of sites `s : ι → ℝ^(m+1)`. -/
def prodCov (Δ : Fin (m + 1) → ℝ) {ι : Type*} (s : ι → Fin (m + 1) → ℝ) :
    Matrix ι ι ℝ :=
  Matrix.of fun a b => ∏ k, Real.exp (-(Δ k) * |s a k - s b k|)

/-- The 1-d exponential covariance is PSD on sites indexed by ANY finite
    type: transport `ouCov_posSemidef_all` along `Fintype.equivFin` with
    `PosSemidef.submatrix`. -/
theorem ouCov_posSemidef_index {ι : Type*} [Finite ι] (Δ : ℝ) (hΔ : 0 ≤ Δ)
    (t : ι → ℝ) :
    (Matrix.of fun a b : ι => Real.exp (-Δ * |t a - t b|)).PosSemidef := by
  have := Fintype.ofFinite ι
  have h := ouCov_posSemidef_all Δ hΔ (t ∘ (Fintype.equivFin ι).symm)
  have heq : (Matrix.of fun a b : ι => Real.exp (-Δ * |t a - t b|))
      = (Matrix.of fun i j =>
          Real.exp (-Δ * |(t ∘ (Fintype.equivFin ι).symm) i
            - (t ∘ (Fintype.equivFin ι).symm) j|)).submatrix
          (Fintype.equivFin ι) (Fintype.equivFin ι) := by
    ext a b
    simp [Matrix.submatrix_apply]
  rw [heq]
  exact h.submatrix _

/-- **The unreflected OU-product covariance is PSD** on any finite site
    family: every coordinate factor is an exponential covariance, and PSD
    survives entrywise products (iterated Schur). The TIME rate needs
    0 ≤ Δ 0 here — unreflected, the time factor is an OU covariance, not a
    rank-one Gram matrix. -/
theorem prodCov_posSemidef (Δ : Fin (m + 1) → ℝ) (hΔ : ∀ k, 0 ≤ Δ k)
    {ι : Type*} [Finite ι] (s : ι → Fin (m + 1) → ℝ) :
    (prodCov Δ s).PosSemidef := by
  have h := SchurProduct.posSemidef_entrywise_prod
    (fun k : Fin (m + 1) =>
      Matrix.of fun a b : ι => Real.exp (-(Δ k) * |s a k - s b k|))
    (fun k => ouCov_posSemidef_index (Δ k) (hΔ k) (fun a => s a k))
  simpa only [Matrix.of_apply] using h

/-! ## 2. The field: a genuine probability measure with this covariance -/

/-- **THE FIELD**: the centred Gaussian measure on `ℝ^sites` whose
    covariance is the OU-product kernel. -/
def fieldMeasure (Δ : Fin (m + 1) → ℝ) {ι : Type*} [Fintype ι] [DecidableEq ι]
    (s : ι → Fin (m + 1) → ℝ) : Measure (EuclideanSpace ℝ ι) :=
  multivariateGaussian 0 (prodCov Δ s)

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

instance isGaussian_fieldMeasure (Δ : Fin (m + 1) → ℝ)
    (s : ι → Fin (m + 1) → ℝ) : IsGaussian (fieldMeasure Δ s) :=
  isGaussian_multivariateGaussian

/-- Each coordinate field ω ↦ ω(a) is square-integrable. -/
theorem memLp_eval (Δ : Fin (m + 1) → ℝ) (s : ι → Fin (m + 1) → ℝ) (a : ι) :
    MemLp (fun ω : EuclideanSpace ℝ ι => ω a) 2 (fieldMeasure Δ s) := by
  have h : (fun ω : EuclideanSpace ℝ ι => ω a)
      = fun ω : EuclideanSpace ℝ ι => ⟪EuclideanSpace.basisFun ι ℝ a, ω⟫ := by
    ext ω
    simp [PiLp.inner_apply]
  rw [h]
  exact MemLp.const_inner _ IsGaussian.memLp_two_id

/-- Each coordinate field has mean zero. -/
theorem integral_eval (Δ : Fin (m + 1) → ℝ) (s : ι → Fin (m + 1) → ℝ) (a : ι) :
    ∫ ω, ω a ∂(fieldMeasure Δ s) = 0 := by
  have h : (fun ω : EuclideanSpace ℝ ι => ω a)
      = fun ω : EuclideanSpace ℝ ι => ⟪EuclideanSpace.basisFun ι ℝ a, ω⟫ := by
    ext ω
    simp [PiLp.inner_apply]
  rw [h]
  have hid : Integrable (fun ω : EuclideanSpace ℝ ι => ω) (fieldMeasure Δ s) :=
    IsGaussian.integrable_id
  rw [integral_inner hid]
  have hzero : ∫ ω, ω ∂(fieldMeasure Δ s) = 0 :=
    integral_id_multivariateGaussian
  rw [hzero, inner_zero_right]

/-- **The two-point function IS the covariance kernel**:
    ∫ ω(a)·ω(b) dμ = Πₖ e^{−Δₖ|s(a)ₖ − s(b)ₖ|}. -/
theorem twoPoint (Δ : Fin (m + 1) → ℝ) (hΔ : ∀ k, 0 ≤ Δ k)
    (s : ι → Fin (m + 1) → ℝ) (a b : ι) :
    ∫ ω, ω a * ω b ∂(fieldMeasure Δ s) = prodCov Δ s a b := by
  have hcov : cov[fun ω : EuclideanSpace ℝ ι => ω a,
      fun ω : EuclideanSpace ℝ ι => ω b; fieldMeasure Δ s] = prodCov Δ s a b :=
    covariance_eval_multivariateGaussian (prodCov_posSemidef Δ hΔ s) a b
  have hsub := covariance_eq_sub (memLp_eval Δ s a) (memLp_eval Δ s b)
  rw [integral_eval, integral_eval, mul_zero, sub_zero] at hsub
  rw [← hcov, hsub]
  simp only [Pi.mul_apply]

/-! ## 3. Measure-level OS2 -/

/-- The doubled site family: N positive-time sites and their reflections. -/
def doubled {N : ℕ} (z : Fin N → Fin (m + 1) → ℝ) :
    Fin N ⊕ Fin N → Fin (m + 1) → ℝ :=
  Sum.elim z (fun j => theta (z j))

/-- **The pairing identity**: the integral of F·F^θ against the field equals
    the reflected covariance form — the bridge from measure to matrix. No
    positivity of times is needed for the EQUALITY. -/
theorem integral_pairing (Δ : Fin (m + 1) → ℝ) (hΔ : ∀ k, 0 ≤ Δ k)
    {N : ℕ} (z : Fin N → Fin (m + 1) → ℝ) (c : Fin N → ℝ) :
    ∫ ω, (∑ i, c i * ω (Sum.inl i)) * (∑ j, c j * ω (Sum.inr j))
        ∂(fieldMeasure Δ (doubled z))
      = ∑ i, ∑ j, c i * c j
          * ∏ k, Real.exp (-(Δ k) * |z i k - theta (z j) k|) := by
  have hexp : ∀ ω : EuclideanSpace ℝ (Fin N ⊕ Fin N),
      (∑ i, c i * ω (Sum.inl i)) * (∑ j, c j * ω (Sum.inr j))
        = ∑ i, ∑ j, (c i * c j) * (ω (Sum.inl i) * ω (Sum.inr j)) := by
    intro ω
    rw [Finset.sum_mul_sum]
    exact Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => by
      ring
  simp_rw [hexp]
  have hterm : ∀ a b : Fin N ⊕ Fin N,
      Integrable (fun ω : EuclideanSpace ℝ (Fin N ⊕ Fin N) => ω a * ω b)
        (fieldMeasure Δ (doubled z)) := by
    intro a b
    exact (memLp_eval Δ (doubled z) a).integrable_mul
      (memLp_eval Δ (doubled z) b)
  rw [integral_finset_sum _ (fun i _ =>
    integrable_finset_sum _ (fun j _ =>
      ((hterm (Sum.inl i) (Sum.inr j)).const_mul (c i * c j))))]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [integral_finset_sum _ (fun j _ =>
    (hterm (Sum.inl i) (Sum.inr j)).const_mul (c i * c j))]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [integral_const_mul, twoPoint Δ hΔ (doubled z) (Sum.inl i) (Sum.inr j)]
  simp only [prodCov, Matrix.of_apply, doubled, Sum.elim_inl, Sum.elim_inr]

/-- **MEASURE-LEVEL REFLECTION POSITIVITY for the OU-product field, in every
    dimension**: the pairing of a linear observable of the positive-time
    sites with its time reflection has NONNEGATIVE integral against the
    field measure. The right side is covariance-level `os2_reflection`. -/
theorem os2_measure_level (Δ : Fin (m + 1) → ℝ) (hΔ : ∀ k, 0 ≤ Δ k)
    {N : ℕ} (z : Fin N → Fin (m + 1) → ℝ) (hpos : ∀ i, 0 ≤ z i 0)
    (c : Fin N → ℝ) :
    0 ≤ ∫ ω, (∑ i, c i * ω (Sum.inl i)) * (∑ j, c j * ω (Sum.inr j))
        ∂(fieldMeasure Δ (doubled z)) := by
  rw [integral_pairing Δ hΔ z c]
  exact os2_reflection Δ (fun k _ => hΔ k) z hpos c

/-- Non-vacuity: at a single site the pairing integral EQUALS
    e^{−2Δ₀x}·c² — with c ≠ 0 a strictly positive number. The measure-level
    statement has content. -/
theorem os2_measure_level_attained (Δ : Fin (m + 1) → ℝ) (hΔ : ∀ k, 0 ≤ Δ k)
    (z : Fin 1 → Fin (m + 1) → ℝ) (h0 : 0 ≤ z 0 0) (c : Fin 1 → ℝ) :
    ∫ ω, (∑ i, c i * ω (Sum.inl i)) * (∑ j, c j * ω (Sum.inr j))
        ∂(fieldMeasure Δ (doubled z))
      = Real.exp (-(Δ 0) * (2 * z 0 0)) * (c 0 * c 0) := by
  rw [integral_pairing Δ hΔ z c]
  exact os2_reflection_attained Δ z h0 c

end OS2MeasureLevel
