/-
  SkewAdjointExponential: the exponential of a skew-adjoint matrix is unitary and, when traceless,
  lands in `SU(n)` — the estate's `su(n)` exponentiates into Mathlib's `specialUnitaryGroup`, and
  the gauge group `SU(4) × SU(2)_L × SU(2)_R` is reached from the estate's own Lie algebra

  Campaign 3 hardening unit 188 (20 September 2026). Spine links L10 (gauge algebra embedding — the
  group level, gap N4), L15 (Higgs sector) and L16 (anomaly cancellation).

  WHY. L16's row says *no group*; L10's says the group level *"has no declaration and rests on the
  `Mₙ(ℂ) → SU(n)` postulate"* (`ASSUMPTIONS_LEDGER` 11); `PatiSalamOnSixteen`'s header says
  *"`SU(4)`, `SU(2)`, `Spin(10)` exist nowhere in the estate"*; `TracelessSkewDimension`'s
  `traceless` is called that and not `su` because *"nothing here says it is the tangent space of a
  smooth group"*, and `TracelessSkewLie` and `PatiSalamStabiliserLie` record that
  `Matrix.specialUnitaryGroup` is mentioned in no file. Queried before writing:
  `specialUnitaryGroup` occurs in `paper_f` in exactly those three prose lines and in no
  declaration; `unitaryGroup` over `ℂ` occurs as `Matrix.unitaryGroup (Fin n) ℂ` in
  `HermitianSignatureEigenvalues.unitaryUnit` and as the Stone chain's own `FiniteStone.unitaryGroup
  H t` (the one-parameter group `e^{itH}` of a self-adjoint operator on a Hilbert space — an
  operator group, not a matrix group); the matrix exponential is used in five files (the cutoff
  chain, `SchurExponential`, `HermiteCompleteness`), never to land in a group. This file puts the
  group there, from the Lie algebra the Higgs units use.

  WHAT IS PROVED, for every `n` (including `0`).
  (1) **`exp_mem_unitaryGroup`**: `X` skew-adjoint ⟹ `exp X ∈ Matrix.unitaryGroup (Fin n) ℂ`
      (`exp X · star (exp X) = exp X · exp (−X) = exp 0 = 1`, by `Matrix.exp_conjTranspose` and
      `Matrix.exp_add_of_commute`).
  (2) **`det_exp_smul_of_isHermitian`**: `H` Hermitian ⟹ `det (exp (c • H)) = exp (c · tr H)` — the
      spectral theorem (`IsHermitian.spectral_theorem`, `eigenvectorUnitary`) diagonalises,
      `Matrix.exp_conj` and `Matrix.det_conj` strip the unitary, `Matrix.exp_diagonal` and
      `det_diagonal` reduce to `∏ exp (c λᵢ) = exp (c ∑ λᵢ)`, and `trace_eq_sum_eigenvalues`
      finishes. Mathlib has no `det (exp A) = exp (tr A)` in any form (queried: `det_exp`,
      `exp_trace` absent), and neither did the estate; this is the Hermitian-direction case, which
      is all the skew-adjoint algebras need.
  (3) `isHermitian_neg_I_smul` (`X` skew-adjoint ⟹ `(−i) • X` Hermitian), hence
      **`det_exp_of_skewAdjoint`**: `det (exp X) = exp (tr X)`, and
      **`exp_mem_specialUnitaryGroup`**:
      `X` skew-adjoint and traceless ⟹ `exp X ∈ Matrix.specialUnitaryGroup (Fin n) ℂ`.
  (4) **`expSU : traceless n → specialUnitaryGroup (Fin n) ℂ`** on this estate's `su(n)`
      (`TracelessSkewDimension.traceless`, the kernel of the imaginary trace on `skewAdjoint`),
      with `expSU_val`; **`oneParam A t := expSU (t • A)`**, the one-parameter subgroup of `SU(n)`
      generated by `A ∈ su(n)`: `oneParam_zero` and **`oneParam_add`** (`exp ((s + t) • A) =
      exp (s • A) · exp (t • A)`, the two summands commuting).
  (5) **`expFull : Full → SU(4) × SU(2) × SU(2)`** — unit 183's `Full = traceless 4 × traceless 2 ×
      traceless 2` exponentiated factor by factor: the Pati–Salam gauge GROUP as a type inhabited
      from the Lie algebra the Higgs units break, with Mathlib's `specialUnitaryGroup` as the group.

  NOT PROVED, said exactly.
  • `ASSUMPTIONS_LEDGER` 11 stands: this file supplies the OBJECT `SU(n)` and the exponential from
    the estate's `su(n)` into it; that the physical gauge group IS this `SU(n)` (rather than another
    group with the same Lie algebra, or `U(n)`, or a quotient) is the postulate, and nothing here
    decides it.
  • Surjectivity of `exp : su(n) → SU(n)` is not proved (it needs the spectral theorem for UNITARY
    matrices, and Mathlib's is for Hermitian ones); nor is `exp` a local diffeomorphism, nor is
    `traceless n` the tangent space of anything — `specialUnitaryGroup` is a `Submonoid`, and no
    manifold, Lie group or topology is put on it here or anywhere in the estate (queried:
    `LieGroup` occurs in no `paper_f` file).
    ⚠ 25 September 2026 (hardening unit 215, `ERRATUM 694`): *or topology … anywhere in the
    estate* is stale since unit 206, which used the subspace topology of the matrices; `U(n)` and
    `SU(n)` are compact (`PatiSalamStabiliserTopology.isCompact_unitaryGroup`,
    `PatiSalamTopologicalCopies.isCompact_specialUnitaryGroup`) and the gauge actions continuous
    (`PatiSalamTopologicalCopies.continuous_stage1_smul`). No manifold or Lie-group structure is
    used in any declaration; the query's word now occurs in four `paper_f` files, all in prose.
    Kept as written (`ERRATUM 94`).
  • `expFull` is a function, not a homomorphism from a group (`Full` is a vector space; `exp` is not
    additive off commuting pairs), and its compatibility with units 178 and 182's representations —
    that `exp A · X · exp(B)ᵀ` integrates the Lie-algebra action `A X + X Bᵀ` — is not stated.
    ⚠ 25 September 2026 (hardening unit 191, `paper_f/PatiSalamGaugeAction.lean`): the
    compatibility is now stated and proved, with the three groups acting as `MulAction`s —
    `hasDerivAt_stage1` (the derivative at `t = 0` of `oneParamG1 p t • X` is `act`),
    `hasDerivAt_stage2LR` (of the `SU(2)_L × SU(2)_R` action, `actEW`) and `hasDerivAt_full`
    (both fields at once, through `expFull`). `expFull` is still not a homomorphism. The bullet
    is kept as written (`ERRATUM 94`).
  • The bracket is untouched: `traceless n` has none here (unit 180's `tracelessSkewLie` has), and
    nothing relates `exp` to it (no Baker–Campbell–Hausdorff, no `exp (Ad)`).

  HYPOTHESES, READ OFF THE BINDERS (`ERRATUM 455`). `exp_mem_unitaryGroup`,
  `isHermitian_neg_I_smul` and `det_exp_of_skewAdjoint` take `X ∈ skewAdjoint`;
  `det_exp_smul_of_isHermitian` takes `H.IsHermitian`; `exp_mem_specialUnitaryGroup` takes
  `X ∈ skewAdjoint` and `trace X = 0`; `expSU`, `expSU_val`, `coe_smul_traceless`, `oneParam`,
  `oneParam_zero`, `oneParam_add` and `expFull` take elements of the subtypes and nothing else. `n`
  is any natural number.

  NEAR-DUPLICATES CHECKED BEFORE WRITING (`ERRATUM 270`: the 13 names run against `paper_f` with
  `newnames_scan`'s regex before this header was written — none taken).
  `HermitianFibreCount.conj_eq` is the same unpacking of the spectral theorem over `ℝ`, not reusable
  over `ℂ`; `FiniteStone. unitaryGroup H t` is a one-parameter group on `E →L[ℂ] E`, not this file's
  `oneParam` in a matrix group; `OrderOneCutoffFactorises` uses `Matrix.exp_diagonal` for `exp (t
  σ₃)` and puts the value in no group.
-/

import PatiSalamTwoStageStabiliser
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.Matrix.Spectrum
import Mathlib.LinearAlgebra.UnitaryGroup

open Matrix Complex NormedSpace TracelessSkewDimension
open scoped Matrix.Norms.Operator

namespace SkewAdjointExponential

variable {n : ℕ}

/-- **The exponential of a skew-adjoint matrix is unitary.** -/
theorem exp_mem_unitaryGroup (X : Matrix (Fin n) (Fin n) ℂ)
    (hX : X ∈ skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) :
    exp X ∈ Matrix.unitaryGroup (Fin n) ℂ := by
  rw [Matrix.mem_unitaryGroup_iff]
  have hs : star X = -X := skewAdjoint.mem_iff.mp hX
  rw [Matrix.star_eq_conjTranspose, ← Matrix.exp_conjTranspose, ← Matrix.star_eq_conjTranspose, hs,
    ← Matrix.exp_add_of_commute X (-X) (Commute.neg_right (Commute.refl X)), add_neg_cancel,
    NormedSpace.exp_zero]

/-- **`det (exp (c • H)) = exp (c · tr H)` for Hermitian `H`**: diagonalise by the spectral theorem,
exponentiate the diagonal, multiply the eigenvalue exponentials. -/
theorem det_exp_smul_of_isHermitian (H : Matrix (Fin n) (Fin n) ℂ) (hH : H.IsHermitian) (c : ℂ) :
    det (exp (c • H)) = Complex.exp (c * trace H) := by
  set U : Matrix (Fin n) (Fin n) ℂ := (hH.eigenvectorUnitary : Matrix (Fin n) (Fin n) ℂ) with hUdef
  have hU : star U * U = 1 := Unitary.coe_star_mul_self hH.eigenvectorUnitary
  have hU' : U * star U = 1 := Unitary.coe_mul_star_self hH.eigenvectorUnitary
  have hspec : H = U * diagonal (fun i => (hH.eigenvalues i : ℂ)) * star U := by
    have h := hH.spectral_theorem
    simpa [Unitary.conjStarAlgAut_apply, Function.comp_def] using h
  have hUunit : IsUnit U := ⟨⟨U, star U, hU', hU⟩, rfl⟩
  have hinv : U⁻¹ = star U := Matrix.inv_eq_left_inv hU
  have hcH : c • H = U * diagonal (fun i => c * (hH.eigenvalues i : ℂ)) * U⁻¹ := by
    conv_lhs => rw [hspec]
    rw [hinv, ← Matrix.smul_mul, ← Matrix.mul_smul, ← Matrix.diagonal_smul]
    rfl
  rw [hcH, Matrix.exp_conj _ _ hUunit, Matrix.det_conj hUunit, Matrix.exp_diagonal, det_diagonal,
    hH.trace_eq_sum_eigenvalues, Finset.mul_sum, Complex.exp_sum]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [Pi.coe_exp, ← Complex.exp_eq_exp_ℂ]
  rfl

/-- A skew-adjoint matrix is `i` times a Hermitian one: `(-i) • X` is Hermitian. -/
theorem isHermitian_neg_I_smul (X : Matrix (Fin n) (Fin n) ℂ)
    (hX : X ∈ skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) : ((-I) • X).IsHermitian := by
  have hs : Xᴴ = -X := by
    rw [← Matrix.star_eq_conjTranspose]; exact skewAdjoint.mem_iff.mp hX
  rw [Matrix.IsHermitian, Matrix.conjTranspose_smul, hs]
  simp [smul_neg, neg_smul]

/-- **`det (exp X) = exp (tr X)` for skew-adjoint `X`.** -/
theorem det_exp_of_skewAdjoint (X : Matrix (Fin n) (Fin n) ℂ)
    (hX : X ∈ skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) :
    det (exp X) = Complex.exp (trace X) := by
  have hH := isHermitian_neg_I_smul X hX
  have hX' : I • ((-I) • X) = X := by rw [smul_smul]; simp
  calc det (exp X) = det (exp (I • ((-I) • X))) := by rw [hX']
    _ = Complex.exp (I * trace ((-I) • X)) := det_exp_smul_of_isHermitian _ hH I
    _ = Complex.exp (trace X) := by rw [trace_smul, smul_eq_mul, ← mul_assoc]; simp

/-- **Traceless skew-adjoint exponentiates into `SU(n)`** — Mathlib's `specialUnitaryGroup`. -/
theorem exp_mem_specialUnitaryGroup (X : Matrix (Fin n) (Fin n) ℂ)
    (hX : X ∈ skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) (htr : trace X = 0) :
    exp X ∈ Matrix.specialUnitaryGroup (Fin n) ℂ :=
  Matrix.mem_specialUnitaryGroup_iff.mpr
    ⟨exp_mem_unitaryGroup X hX, by rw [det_exp_of_skewAdjoint X hX, htr, Complex.exp_zero]⟩

/-- The exponential of an element of this estate's `traceless n` (`su(n)` as a subspace), as an
element of `SU(n)`. -/
noncomputable def expSU (A : traceless n) : Matrix.specialUnitaryGroup (Fin n) ℂ :=
  ⟨exp ((A : skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) : Matrix (Fin n) (Fin n) ℂ),
    exp_mem_specialUnitaryGroup _ (A : skewAdjoint (Matrix (Fin n) (Fin n) ℂ)).2
      (trace_eq_zero_of_mem_traceless A.2)⟩

theorem expSU_val (A : traceless n) :
    (expSU A : Matrix (Fin n) (Fin n) ℂ)
      = exp ((A : skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) : Matrix (Fin n) (Fin n) ℂ) := rfl

/-- The one-parameter subgroup `t ↦ exp (t • A)` of `SU(n)` generated by `A ∈ su(n)`. -/
noncomputable def oneParam (A : traceless n) (t : ℝ) : Matrix.specialUnitaryGroup (Fin n) ℂ :=
  expSU (t • A)

theorem coe_smul_traceless (A : traceless n) (t : ℝ) :
    (((t • A : traceless n) : skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) : Matrix (Fin n) (Fin n) ℂ)
      = t • ((A : skewAdjoint (Matrix (Fin n) (Fin n) ℂ)) : Matrix (Fin n) (Fin n) ℂ) := by
  rw [Submodule.coe_smul, skewAdjoint.val_smul]
  rfl

theorem oneParam_zero (A : traceless n) : oneParam A 0 = 1 := by
  apply Subtype.ext
  simp [oneParam, expSU_val]

theorem oneParam_add (A : traceless n) (s t : ℝ) :
    oneParam A (s + t) = oneParam A s * oneParam A t := by
  apply Subtype.ext
  simp only [Submonoid.coe_mul, oneParam, expSU_val, coe_smul_traceless, add_smul]
  exact Matrix.exp_add_of_commute _ _ (((Commute.refl _).smul_left s).smul_right t)

/-- **The gauge group `SU(4) × SU(2)_L × SU(2)_R`, reached from the estate's own Lie algebra**: the
exponential of an element of unit 183's `Full = su(4) ⊕ su(2) ⊕ su(2)`, factor by factor. -/
noncomputable def expFull (p : PatiSalamTwoStageStabiliser.Full) :
    Matrix.specialUnitaryGroup (Fin 4) ℂ × Matrix.specialUnitaryGroup (Fin 2) ℂ
      × Matrix.specialUnitaryGroup (Fin 2) ℂ :=
  (expSU p.1, expSU p.2.1, expSU p.2.2)

end SkewAdjointExponential
