/-
  SpinKernel.lean — the kernel of the vector representation is exactly
  ±1. One of W7 step (d)'s three parts, closed.

  WHERE THIS SITS. `SpinVectorRep` proved ±1 ⊆ kernel: −1 is a spin
  element and it acts as the identity, and `x` and `−x` induce the same
  map. The other inclusion — that NOTHING ELSE acts trivially — was
  recorded as research-level in WALLS W7 from the day the wall was
  written, and re-copied in every entry since. It is not. Asked
  PROOF_STRATEGY §6's STAIRCASE question directly, it is four steps,
  three of them short, and this file walks them.

  THE ROUTE:
  (i) A spin element acting trivially commutes with every vector —
      immediate from `ι_spinToEndo` and `ι_injective`.
  (ii) Commuting with every vector makes it central, because the
      Clifford algebra is generated by the image of `ι`. One induction.
  (iii) The centre of Cl(1,3;ℝ) is ℝ. This is the work, and Mathlib
      supplies none of it: there is no ring-centre theorem for a matrix
      algebra and nothing about the centre of the quaternions. Both are
      built below, §1 and §2, and transported along the estate's
      `cliffordRealMinkowskiEquiv`.
  (iv) A central unitary element is ±1: it is a scalar, `star` fixes
      scalars, so its square is 1.

  WHAT THIS FILE PROVES:
  1. **`quaternion_central`** — a quaternion commuting with every
     quaternion is real. Mathlib has no such statement:
     `Quaternion.mem_center_iff` does not exist and
     `Algebra.IsCentral ℝ ℍ[ℝ]` is not an instance.
  2. **`matrix2H_central`** — a 2×2 quaternionic matrix commuting with
     everything is a real scalar. Mathlib has no ring-centre theorem
     for matrix algebras; `SpecialLinearGroup.mem_center_iff` is about
     the GROUP centre of SLₙ, which is a different statement.
  3. **`clifford_central`** — hence the centre of Cl(1,3;ℝ) is ℝ,
     available only because the isomorphism to M₂(ℍ) is bundled.
  4. **`central_of_comm_ι`** — commuting with the vectors is enough.
  5. **`kernel_eq_pm_one`** — **the kernel of the vector representation
     is contained in ±1.**
  6. **`kernel_iff`** — and the converse, so the kernel is EXACTLY ±1
     as a biconditional rather than as two facts a reader has to put
     together. Added by review round 22, which pointed out that the
     file proved one inclusion and asserted the other in prose.

  WHAT THIS DOES NOT DO. Step (d)'s other two parts are untouched and
  are NOT reclassified by this: that the image lands in the identity
  component SO⁺(1,3), and that the map is onto it, remain
  research-level. Knowing the kernel does not tell you the image.

  Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new
  axioms.
-/

import CliffordRealMinkowski
import SpinVectorRep

open CliffordAlgebra CliffordRealMinkowski SpinVectorRep
open scoped Quaternion

noncomputable section

namespace SpinKernel

/-! ## 1. The centre of the quaternions is ℝ

Mathlib does not have this — **re-verified 11 Aug 2026 by shape**, not just by
name: 148 statements in the pinned environment mention `Quaternion` and not one
mentions a centre, and `Algebra.IsCentral` has no instance for `ℍ[ℝ]`. Two
commutators are enough: with `i` and with `j`. -/

theorem quaternion_central {a : ℍ[ℝ]} (h : ∀ q : ℍ[ℝ], a * q = q * a) :
    a = (algebraMap ℝ ℍ[ℝ]) a.re := by
  have hi := h qi
  have hj := h qj
  rw [Quaternion.ext_iff] at hi hj
  simp [qi, qj] at hi hj
  rw [Quaternion.ext_iff]
  refine ⟨rfl, ?_, ?_, ?_⟩ <;> simp <;> linarith [hi.1, hi.2, hj.1, hj.2]

/-! ## 2. The centre of M₂(ℍ) is ℝ

**"Also absent from Mathlib" — THAT WAS FALSE, corrected 11 Aug 2026,
`ERRATUM 119`.** `Matrix.subsemigroupCenter_eq_scalar_map` is in Mathlib and is
stated over `[Semiring α]` — **no commutativity**, so the quaternionic entries
are no obstacle — giving the centre of the matrix semigroup as the image of the
base's centre under `Matrix.scalar`. `Matrix.center_eq_range` sits beside it for
the commutative case. The original probe searched names (`Matrix.mem_center_iff`
and neighbours) and missed by a suffix; a shape probe returns both at once.
`QuaternionCenter.mem_matrixCenter_iff` states the consequence for **every**
index type, where this section's theorem is `Fin 2` only.

**The hand proof below is kept and is not weakened.** It is self-contained,
it is what the rest of this file consumes, and rewriting a working proof to
route through a library lemma found afterwards would be churn. What was wrong
was the sentence, not the mathematics.

Three test matrices: the idempotent `E₀₀`
forces the off-diagonal entries to vanish, the unit `E₀₁` forces the two
diagonal entries equal, and the scalar quaternion matrices force that
common entry central in ℍ, hence real by §1. -/

theorem matrix2H_central {X : Matrix (Fin 2) (Fin 2) ℍ[ℝ]}
    (h : ∀ Y, X * Y = Y * X) :
    ∃ c : ℝ, X = algebraMap ℝ (Matrix (Fin 2) (Fin 2) ℍ[ℝ]) c := by
  -- off-diagonal entries vanish
  have h00 := h (Matrix.single 0 0 1)
  have hoff01 : X 0 1 = 0 := by
    have := congrFun (congrFun h00 0) 1
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.single] using this.symm
  have hoff10 : X 1 0 = 0 := by
    have := congrFun (congrFun h00 1) 0
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.single] using this
  -- the diagonal entries agree
  have h01 := h (Matrix.single 0 1 1)
  have hdiag : X 0 0 = X 1 1 := by
    have := congrFun (congrFun h01 0) 1
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.single] using this
  -- and the common entry is central in ℍ
  have hcent : ∀ q : ℍ[ℝ], X 0 0 * q = q * X 0 0 := by
    intro q
    have := congrFun (congrFun (h (Matrix.diagonal fun _ => q)) 0) 0
    simpa [Matrix.mul_apply, Fin.sum_univ_two, Matrix.diagonal, hoff01] using this
  refine ⟨(X 0 0).re, ?_⟩
  refine Matrix.ext fun i j => ?_
  have hq := quaternion_central hcent
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.algebraMap_eq_diagonal, Matrix.diagonal, hoff01, hoff10,
      ← hdiag, ← hq]

/-! ## 3. The centre of Cl(1,3;ℝ) is ℝ

Transported along the estate's bundled isomorphism. This is the third
payoff from building it as an `AlgEquiv` rather than an existence
statement. -/

theorem clifford_central {x : Cl} (h : ∀ y : Cl, x * y = y * x) :
    ∃ c : ℝ, x = algebraMap ℝ Cl c := by
  have hY : ∀ Y, cliffordRealMinkowskiEquiv x * Y = Y * cliffordRealMinkowskiEquiv x := by
    intro Y
    obtain ⟨y, rfl⟩ := cliffordRealMinkowskiEquiv.surjective Y
    rw [← map_mul, ← map_mul, h y]
  obtain ⟨c, hc⟩ := matrix2H_central hY
  refine ⟨c, ?_⟩
  apply cliffordRealMinkowskiEquiv.injective
  rw [hc, AlgEquiv.commutes]

/-! ## 4. Commuting with the vectors is enough

The Clifford algebra is generated by the image of `ι`, so an element
commuting with every vector commutes with everything. Mathlib's
`CliffordAlgebra.induction` has exactly the four cases needed. -/

theorem central_of_comm_ι {x : Cl} (h : ∀ v : V, x * ι Q₁₃ v = ι Q₁₃ v * x) :
    ∀ y : Cl, x * y = y * x := by
  intro y
  induction y using CliffordAlgebra.induction with
  | algebraMap r => rw [Algebra.commutes]
  | ι v => exact h v
  | mul a b ha hb => rw [← mul_assoc, ha, mul_assoc, hb, mul_assoc]
  | add a b ha hb => rw [mul_add, add_mul, ha, hb]

/-! ## 5. The kernel -/

/-- A spin element acting trivially on ℝ⁴ commutes with every vector. -/
theorem comm_ι_of_trivial {x : Clˣ} (hx : (x : Cl) ∈ spinGroup Q₁₃)
    (hact : ∀ v : V, spinToEndo hx v = v) (v : V) :
    (x : Cl) * ι Q₁₃ v = ι Q₁₃ v * (x : Cl) := by
  have h := ι_spinToEndo hx v
  rw [hact v] at h
  calc (x : Cl) * ι Q₁₃ v
      = (x : Cl) * ι Q₁₃ v * (((x⁻¹ : Clˣ) : Cl) * (x : Cl)) := by
        rw [Units.inv_mul, mul_one]
    _ = ((x : Cl) * ι Q₁₃ v * ((x⁻¹ : Clˣ) : Cl)) * (x : Cl) := by
        simp only [mul_assoc]
    _ = ι Q₁₃ v * (x : Cl) := by rw [← h]

/-- **The kernel of the vector representation is contained in ±1.**
    With `SpinVectorRep.spinToEndo_neg_one` for the reverse inclusion,
    the kernel is exactly ±1 — closing one of W7 step (d)'s three
    parts. -/
theorem kernel_eq_pm_one {x : Clˣ} (hx : (x : Cl) ∈ spinGroup Q₁₃)
    (hact : ∀ v : V, spinToEndo hx v = v) :
    (x : Cl) = 1 ∨ (x : Cl) = -1 := by
  obtain ⟨c, hc⟩ := clifford_central (central_of_comm_ι (comm_ι_of_trivial hx hact))
  have hstar : star (x : Cl) * (x : Cl) = 1 := hx.1.2.1
  rw [hc, star_algebraMap, ← map_mul] at hstar
  have hc1 : c * c = 1 := by
    apply FaithfulSMul.algebraMap_injective ℝ Cl
    rw [hstar, map_one]
  have : (c - 1) * (c + 1) = 0 := by ring_nf; linarith [hc1]
  rcases mul_eq_zero.mp this with h | h
  · left; rw [hc, show c = 1 by linarith, map_one]
  · right
    rw [hc, show c = -1 by linarith]
    simp

/-! ## 6. The kernel is exactly ±1

Review round 22's fold. §5 proves one inclusion and the header asserted
the other by pointing at `SpinVectorRep.spinToEndo_neg_one`. That is two
facts a reader has to assemble, and one of them was prose. Here is the
biconditional. -/

/-- ±1 acts trivially. The two signs cancel because the inverse of ±1
    is itself. -/
theorem trivial_of_pm_one {x : Clˣ} (hx : (x : Cl) ∈ spinGroup Q₁₃)
    (h : (x : Cl) = 1 ∨ (x : Cl) = -1) (v : V) : spinToEndo hx v = v := by
  have hmul := Units.mul_inv x
  apply ι_injective
  rw [ι_spinToEndo]
  rcases h with h | h
  · rw [h, one_mul] at hmul
    rw [h, one_mul, hmul, mul_one]
  · rw [h, neg_one_mul] at hmul
    have hy : ((x⁻¹ : Clˣ) : Cl) = -1 := neg_eq_iff_eq_neg.mp hmul
    rw [h, hy]
    simp

/-- **The kernel of the vector representation is EXACTLY ±1.** One of
    W7 step (d)'s three parts, stated as the equality it is.

    The other two parts are untouched: this says nothing about the
    image landing in SO⁺(1,3), nor about surjectivity onto it.

    **SUPERSEDED 8 AUG 2026**: both are now proved —
    `SpinOrthochronous.spinToO13_mem_SOplus13` and
    `SpinSurjective.spin_surjective`. Sentence left standing per the
    house rule. -/
theorem kernel_iff {x : Clˣ} (hx : (x : Cl) ∈ spinGroup Q₁₃) :
    (∀ v : V, spinToEndo hx v = v) ↔ ((x : Cl) = 1 ∨ (x : Cl) = -1) :=
  ⟨kernel_eq_pm_one hx, trivial_of_pm_one hx⟩

end SpinKernel
