/-
  SpinBoost.lean — the spin group of Q₁₃ contains genuine boosts, and
  its action on ℝ⁴ moves the time axis.

  THE DOUBT THIS SETTLES. Mathlib's `pinGroup` asks its elements to be
  `unitary`: `star x * x = 1`. For a single generating vector that
  forces `Q₁₃ v = −1`, because `star (ι v) = −ι v` and so
  `star (ι v) * ι v = −Q₁₃ v`. With the mostly-minus form `Q₁₃ v = −1`
  means v is SPACELIKE. Read carelessly that says the group is
  generated by spacelike reflections and its image is the rotation
  group SO(3) — in which case `spinGroup Q₁₃` would have nothing to do
  with the Lorentz group and every theorem in `SpinVectorRep` and
  `SpinToOrthogonal` would be about a compact group wearing a
  Minkowski costume.

  It is not so, and the reason is that the condition on a PRODUCT is
  multiplicative: for `x = ι v₁ · ι v₂`,
  `star x * x = Q₁₃ v₁ · Q₁₃ v₂`, which is 1 when BOTH are +1 as well
  as when both are −1. Two TIMELIKE unit vectors therefore give a spin
  element, and the product of two timelike reflections is a boost.

  WHAT THIS FILE PROVES:
  1. `B = ι(e₀) · ι(w)` with `w = (5/4, 3/4, 0, 0)` is a spin element
     (`B_mem`) — both generating vectors timelike, `Q₁₃ = +1` each.
  2. **`spinToEndo_B`** — its action on ℝ⁴ computed in full:
     `(t,x,y,z) ↦ (17/8·t − 15/8·x, 17/8·x − 15/8·t, y, z)`. That is
     the Lorentz boost with `cosh = 17/8`, `sinh = −15/8`; the identity
     `17² − 15² = 8²` is why these rationals were chosen.
  3. **`spinToEndo_B_e₀_ne`** — the time axis MOVES. No rotation does
     that, so the image of the vector representation is not contained
     in the stabiliser of `e₀`. This is the first thing the estate has
     proved about the IMAGE in step (d)'s sense, and it is a negative
     statement: it rules the rotation group out, it does not identify
     the image with SO⁺(1,3).
  4. **`boost_rot_ne_rot_boost`** — the boost and the π-rotation of
     `SpinVectorRep` do not commute. Review round 17 recorded this as a
     check it could not make: the multiplication order on the
     orthogonal group, `(f * g) x = f (g x)`, is only load-bearing if
     the group is nonabelian, and every π-rotation available then
     commuted with every other (they form a Klein four-group). This
     supplies the missing witness, so the order convention is now
     pinned by a refutation rather than by a `rfl`.

  Everything rests on Mathlib's `ι_mul_ι_mul_ι`:
  `ι a * ι b * ι a = ι (polar Q a b • a − Q a • b)`, the reflection
  formula, which needs no invertibility hypotheses. Conjugation by a
  product of two vectors is two applications of it.

  NOT proven here, and unchanged: that the image is SO⁺(1,3), that the
  map is onto it, or that the kernel is no larger than ±1. Knowing the
  image contains a boost and a rotation and is nonabelian is a long way
  from knowing what it is.

  Machine verification: Lean 4.29.1 + Mathlib v4.29.1. 0 sorry, 0 new
  axioms.
-/

import SpinVectorRep

open CliffordAlgebra CliffordRealMinkowski SpinVectorRep

noncomputable section

namespace SpinBoost

/-! ## 1. Two timelike unit vectors -/

/-- A second timelike unit vector, not parallel to `e₀`. The entries are
    `(5/4, 3/4)` because `5² − 3² = 4²`, so `Q₁₃ w = 1` exactly. -/
def w : V := ((5/4, 3/4), (0, 0))

theorem Q₁₃_w : Q₁₃ w = 1 := by rw [Q₁₃_apply]; norm_num [w]

theorem ι_e₀_sq : ι Q₁₃ e₀ * ι Q₁₃ e₀ = 1 := by
  rw [ι_sq_scalar, Q₁₃_e₀]; simp

theorem ι_w_sq : ι Q₁₃ w * ι Q₁₃ w = 1 := by
  rw [ι_sq_scalar, Q₁₃_w]; simp

/-- `ι e₀` as a unit: it squares to +1, so it is its own inverse. -/
def E₀ : Clˣ where
  val := ι Q₁₃ e₀
  inv := ι Q₁₃ e₀
  val_inv := ι_e₀_sq
  inv_val := ι_e₀_sq

/-- `ι w` as a unit. -/
def W : Clˣ where
  val := ι Q₁₃ w
  inv := ι Q₁₃ w
  val_inv := ι_w_sq
  inv_val := ι_w_sq

/-- **The boost**, as a product of two timelike reflections. -/
def B : Clˣ := E₀ * W

theorem B_val : (B : Cl) = ι Q₁₃ e₀ * ι Q₁₃ w := rfl

theorem B_inv : ((B⁻¹ : Clˣ) : Cl) = ι Q₁₃ w * ι Q₁₃ e₀ := rfl

theorem E₀_mem : E₀ ∈ lipschitzGroup Q₁₃ := Subgroup.subset_closure ⟨e₀, rfl⟩
theorem W_mem : W ∈ lipschitzGroup Q₁₃ := Subgroup.subset_closure ⟨w, rfl⟩

/-- **`B` is a spin element.** The unitarity check is the whole point of
    the file: `star B * B = Q₁₃ e₀ · Q₁₃ w = 1 · 1`, so the two `+1`s
    multiply to 1 exactly as the two `−1`s do for a rotation. A SINGLE
    timelike vector would fail here, which is what makes the naive
    reading ("unitary forces spacelike, so the group is SO(3)") wrong. -/
theorem B_mem : (B : Cl) ∈ spinGroup Q₁₃ := by
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · exact lipschitzGroup.coe_mem_iff_mem.2 (mul_mem E₀_mem W_mem)
  · change star (ι Q₁₃ e₀ * ι Q₁₃ w) * (ι Q₁₃ e₀ * ι Q₁₃ w) = 1
    rw [star_mul, star_ι, star_ι]
    calc -ι Q₁₃ w * -ι Q₁₃ e₀ * (ι Q₁₃ e₀ * ι Q₁₃ w)
        = ι Q₁₃ w * ((ι Q₁₃ e₀ * ι Q₁₃ e₀) * ι Q₁₃ w) := by
          simp only [neg_mul, mul_neg, neg_neg, mul_assoc]
      _ = 1 := by rw [ι_e₀_sq, one_mul, ι_w_sq]
  · change (ι Q₁₃ e₀ * ι Q₁₃ w) * star (ι Q₁₃ e₀ * ι Q₁₃ w) = 1
    rw [star_mul, star_ι, star_ι]
    calc ι Q₁₃ e₀ * ι Q₁₃ w * (-ι Q₁₃ w * -ι Q₁₃ e₀)
        = ι Q₁₃ e₀ * ((ι Q₁₃ w * ι Q₁₃ w) * ι Q₁₃ e₀) := by
          simp only [neg_mul, mul_neg, neg_neg, mul_assoc]
      _ = 1 := by rw [ι_w_sq, one_mul, ι_e₀_sq]
  · exact ι_mul_ι_mem_evenOdd_zero Q₁₃ e₀ w

/-! ## 2. The two polar forms, in coordinates -/

theorem polar_e₀ (v : V) : QuadraticMap.polar Q₁₃ e₀ v = 2 * v.1.1 := by
  obtain ⟨⟨t, x⟩, ⟨y, z⟩⟩ := v
  simp only [QuadraticMap.polar, Q₁₃_apply, e₀, Prod.fst_add, Prod.snd_add]
  ring

theorem polar_w (v : V) :
    QuadraticMap.polar Q₁₃ w v = 5 / 2 * v.1.1 - 3 / 2 * v.1.2 := by
  obtain ⟨⟨t, x⟩, ⟨y, z⟩⟩ := v
  simp only [QuadraticMap.polar, Q₁₃_apply, w, Prod.fst_add, Prod.snd_add]
  ring

/-! ## 3. The action -/

/-- The Lorentz boost in the `t`–`x` plane with `cosh = 17/8` and
    `sinh = −15/8`. -/
def boostTX : V → V := fun v =>
  ((17 / 8 * v.1.1 - 15 / 8 * v.1.2, 17 / 8 * v.1.2 - 15 / 8 * v.1.1),
    (v.2.1, v.2.2))

/-- Conjugation by `B` is two reflections, and their composite is the
    boost. -/
theorem conj_B (v : V) :
    (B : Cl) * ι Q₁₃ v * ((B⁻¹ : Clˣ) : Cl) = ι Q₁₃ (boostTX v) := by
  rw [B_val, B_inv]
  calc ι Q₁₃ e₀ * ι Q₁₃ w * ι Q₁₃ v * (ι Q₁₃ w * ι Q₁₃ e₀)
      = ι Q₁₃ e₀ * (ι Q₁₃ w * ι Q₁₃ v * ι Q₁₃ w) * ι Q₁₃ e₀ := by
        simp only [mul_assoc]
    _ = ι Q₁₃ e₀ * ι Q₁₃ (QuadraticMap.polar Q₁₃ w v • w - Q₁₃ w • v)
          * ι Q₁₃ e₀ := by rw [ι_mul_ι_mul_ι]
    _ = ι Q₁₃ (QuadraticMap.polar Q₁₃ e₀
            (QuadraticMap.polar Q₁₃ w v • w - Q₁₃ w • v) • e₀
          - Q₁₃ e₀ • (QuadraticMap.polar Q₁₃ w v • w - Q₁₃ w • v)) := by
        rw [ι_mul_ι_mul_ι]
    _ = ι Q₁₃ (boostTX v) := by
        congr 1
        obtain ⟨⟨t, x⟩, ⟨y, z⟩⟩ := v
        rw [polar_w, Q₁₃_w, Q₁₃_e₀, polar_e₀]
        simp only [boostTX, w, e₀, Prod.smul_mk, Prod.mk_sub_mk, smul_eq_mul,
          one_smul, Prod.mk.injEq]
        norm_num
        constructor <;> ring

/-- **The action of the boost on ℝ⁴.** -/
theorem spinToEndo_B (v : V) : spinToEndo B_mem v = boostTX v := by
  apply ι_injective
  rw [ι_spinToEndo, conj_B]

/-! ## 4. What it rules out -/

/-- **The time axis moves.** Every rotation fixes `e₀`; this does not,
    so the image of the vector representation is not contained in the
    stabiliser of the time direction. A negative result: it rules the
    rotation group out, it does not identify the image. -/
theorem spinToEndo_B_e₀_ne : spinToEndo B_mem e₀ ≠ e₀ := by
  rw [spinToEndo_B]
  intro h
  have h1 : (boostTX e₀).1.1 = (e₀ : V).1.1 := by rw [h]
  norm_num [boostTX, e₀] at h1

/-- The boosted time axis, computed. -/
theorem boostTX_e₀ : boostTX e₀ = ((17 / 8, -(15 / 8)), (0, 0)) := by
  norm_num [boostTX, e₀]

/-- **The boost and the π-rotation do not commute.** Round 17 wanted
    this and could not get it: the π-rotations alone form a Klein
    four-group, so nothing among them witnesses non-commutativity, and
    without a witness the composition order `(f * g) x = f (g x)` is
    pinned only by a definitional `rfl`. A boost supplies the witness. -/
theorem boost_rot_ne_rot_boost :
    ∃ v : V, boostTX (rotXY v) ≠ rotXY (boostTX v) := by
  refine ⟨((0, 1), (0, 0)), ?_⟩
  intro h
  have h1 : (boostTX (rotXY ((0, 1), (0, 0)))).1.1
      = (rotXY (boostTX ((0, 1), (0, 0)))).1.1 := by rw [h]
  norm_num [boostTX, rotXY] at h1

end SpinBoost
